### ISSUE TITLE
Removing fixed widths on roots

### ISSUE THREAD

**Issue by atakantepe** [primefaces/primevue-tailwind#100]

**Comment by TheZlodziej** [comment]
Some of the elements (eg. number inputs) in input group lack w-[1%] and flex-auto classes.
![image](https://github.com/primefaces/primevue-tailwind/assets/33941527/56582ca8-a43e-412b-a58f-4e57455cfc84)

Also, Dropdown is completely broken when it comes to widths. I fixed it temporary by hiding selected option when on small screen.

**Comment by atakantepe** [comment]
Hi, this one is fixed here: https://github.com/primefaces/primevue-tailwind/issues/124. I will be checking other presets for these types of issues. If you see another one, please add to this issue or open a new one.
