### ISSUE TITLE
Missing preset for VirtualScroller

### ISSUE THREAD

**Issue by eboileau** [primefaces/primevue-tailwind#108]
VirtualScroller is missing, it doesn't work either in the docs for the [DataTable](https://tailwind.primevue.org/datatable/#virtualscroll). That's exactly the use case I need. I managed to create something for the FileUpload, but I am struggling with this one... I'm trying build a preset based on the [VirtualScroller API](https://primevue.org/virtualscroller/), and looking at the _VirtualScrollerStyle.js_ from PrimeVue lib for styling. I am defining root, content, spacer, loader, and loadingIcon, based on PT options, but w/o any props, just basic style, to no avail...  

Any idea when this could be available, or do you have a snippet I could use as a template preset? 

BTW, I like your approach with presets for unstyled mode using Tailwind, this is now much cleaner, and the docs are very well explaining the merge customization, thanks!

**Comment by mertsincan** [comment]
Hi,

VirtualScroller is a base API. So we don't remove its styles for unstyled mode. But you can pass classes, etc. to it with pt.
Please try;
```
<DataTable :pt="{
    virtualScroller: {
             root: 'TEST_CLASS'
    }
}"
```

Best Regards,

**Comment by eboileau** [comment]
Thanks @mertsincan for your quick reply, but then I don't understand why it doesn't work...

This is my `main.js`

```js
// presets
import PrimeVue from 'primevue/config'
import WindScm from '@/presets/windscm'
...
app.use(PrimeVue, { unstyled: true, pt: WindScm, ripple: true })
```

Then in some view

```html
<template>
      <div>
        <DataTable
          :value="records"
          ref="dt"
          sortMode="multiple"
          removableSort
          scrollable
          scrollHeight="400px"
          :virtualScrollerOptions="{ itemSize: 46 }"
          tableStyle="min-w-{50rem}"
        >
        ...
        </DataTable>
     ...
    </div>
</template>
```

Nothing shows up in my table. Same as in the docs here https://tailwind.primevue.org/datatable/#virtualscroll
Am I missing something?
