### ISSUE TITLE
Add ability to add Prefix for Wind presets

### ISSUE THREAD

**Issue by antonbehaeghe** [primefaces/primevue-tailwind#110]
Would it be possible to add the ability to the Wind preset docs pages to add a prefix?

We use the tailwind prefix option, and it's quite tedious now to copypaste the preset, and then manually add the prefix. It would be nice if this could be added automatically.

**Comment by mertsincan** [comment]
Hi,

For now, we don't think it. But, I made some changes in mergeProps option of ptOptions. I think you can use output class string and then add prefix to each class part. https://github.com/primefaces/primevue/issues/4707#issuecomment-1914607040

```
const addPrefix = (classes) => {
     return classes?.spit(' ').map((c) => ....).join(' '); // you can update this block according to your needs.
}

const customMergeProps = (globalPTProps = {}, selfPTProps = {}, datasets) => {
   /*
    * - mergeProps from Vue package
    */
   const mergedProps = Vue.mergeProps(globalPTProps, selfPTProps, datasets);
   const newClassesWithPrefix = addPrefix(mergedProps?.class);

    mergedProps.class = newClassesWithPrefix;

    return mergedProps;
}
```

Best Regards,
