### ISSUE TITLE
Checkbox not working using latest lara preset

### ISSUE THREAD

**Issue by sergeydus** [primefaces/primevue-tailwind#111]
in the image below, a checkbox is supposed to appear in the yellow slot, however, nothing renders inside
<img width="267" alt="image" src="https://github.com/primefaces/primevue-tailwind/assets/29180697/d920e6ab-881e-43d9-8a3e-0a0576891c5b">

https://stackblitz.com/edit/r6zper-8camc5?file=src%2FApp.vue

**Comment by mertsincan** [comment]
Thanks a lot for the report! It has been already fixed for the next version.

Best Regards,
