### ISSUE TITLE
Checkbox and TriStateCheckbox context do not include focus properties

### ISSUE THREAD

**Issue by adambergman** [primefaces/primevue-tailwind#113]
The tailwind themes reference `context.focus` but that property is not included in `CheckboxContext` or `TriStateCheckboxContext`. This is leading to typescript errors.

I'm not sure if the context type were meant to extend another interface that supplies `focused` and this is an issue with the core package's definitions or if the theme being implemented using a property on the context that doesn't exist.

**Checkbox**

https://github.com/primefaces/primevue-tailwind/blob/01ab00369d8b1b110e73a2e16a43a89dcaa663c9/presets/wind/checkbox/index.js#L42

```ts
export interface CheckboxContext {
    /**
     * Current checked state of the item as a boolean.
     * @defaultValue false
     */
    checked: boolean;
    /**
     * Current disabled state of the item as a boolean.
     * @defaultValue false
     */
    disabled: boolean;
}
```

https://github.com/primefaces/primevue/blob/f24b20d5318e7e4012fc4e039fec2057ac540b1b/components/lib/checkbox/Checkbox.d.ts#L193-L204

**TriStateCheckbox**

https://github.com/primefaces/primevue-tailwind/blob/01ab00369d8b1b110e73a2e16a43a89dcaa663c9/presets/wind/tristatecheckbox/index.js#L28

```ts
export interface TriStateCheckboxContext {
    /**
     * Current active state as a boolean.
     * @defaultValue false
     */
    active: boolean;
    /**
     * Current disabled state as a boolean.
     * @defaultValue false
     */
    disabled: boolean;
}
```

https://github.com/primefaces/primevue/blob/f24b20d5318e7e4012fc4e039fec2057ac540b1b/components/lib/tristatecheckbox/TriStateCheckbox.d.ts#L108-L119

**Comment by mertsincan** [comment]
Hi,

We removed the `focused` params from context. https://github.com/primefaces/primevue/issues/5071 And we updated our preset in the next version. We'll release it asap.

Best Regards,
