### ISSUE TITLE
Tooltip Directive: extending the tooltip directive doesn't seem to work 

### ISSUE THREAD

**Issue by mbaljeetsingh** [primefaces/primevue-tailwind#125]
Hi

I'm trying to extend the tooltip directive. But, it doesn't get the styles correctly.

Demo: https://stackblitz.com/edit/kcuyyb-kqnrkv?file=src%2FApp.vue,src%2Fcomponents%2FTooltip.js

In the above demo, the badge directive works properly after extending but not the tooltip. 
<img width="1165" alt="image" src="https://github.com/primefaces/primevue-tailwind/assets/872762/df55774b-0d93-4e50-92d6-2fe5494aa0c7">

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
