### ISSUE TITLE
TabView: doesn't work with Local pt prop 

### ISSUE THREAD

**Issue by mbaljeetsingh** [primefaces/primevue-tailwind#126]
Describe the bug
While creating a library on top of Primevue, I'm trying to convert TabView with local passthrough prop, but I'm not seeing anything in the output after passing the correct data.

Reproducer
https://stackblitz.com/edit/kcuyyb-mx58er?file=src%2Fcomponents%2FTabView.vue,src%2Fcomponents%2FTabPanel.vue,src%2FApp.vue

PrimeVue version
3.47.2

Vue version
3.x

Language
TypeScript

Build / Runtime
Vue CLI App

Browser(s)
No response

Steps to reproduce the behavior
No response

Expected behavior
No response

**Comment by atakantepe** [comment]
Hi, this issue has likely been resolved in the latest updates.
If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.
