### ISSUE TITLE
Primevue Tailwind - setting `class="w-<size>"` does not work on Sidebar

### ISSUE THREAD

**Issue by hugoJuhel** [primefaces/primevue-tailwind#129]
# Bug 
The [documentation](https://tailwind.primevue.org/sidebar/#size) states that the Sidebar's size can be configured through the `class` attribute, but the sidebar ignores the class attribute.

# Expected behavior
Either the size should be settable through the `w-<>` class or the documentation should be updated to remove the size section since it's misleading.

# Reroduce
- Start a fresh Nuxt project 
- Install Tailwind, as a nuxt-module, as per tailwind documentation
- Install primevue-Tailwind as per Primevue documentation
- Copy-paste the `Sidebar` example from the primevue documentation into `app.vue`
- Try updating the width class (`w-full`, `w-1/2`) and note that nothing changes.

# Stackblitz

[Here is stackblitz environnement](https://stackblitz.com/~/github.com/hugoJuhel/primeBug)

# Versions 

- primevue : 3.48.1
- vue : 3.4.15
- nuxt-primevue : 0.3.0

**Comment by aurelien-cd** [comment]
I can confirm this issue.

**Comment by atakantepe** [comment]
Hi, sorry for the late response. I'll check with the PrimeVue team for this issue. I'll remove the size section from the documentation as you suggested.

**Comment by nachodd** [comment]
I've noted the same. Using a custom class and the @apply directive (and applying the width style there) worked for me.

**Comment by Ciscodefran** [comment]
@hugoJuhel How did you make it work?

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
