### ISSUE TITLE
Add Filled State for Inputs [FloatLabel]

### ISSUE THREAD

**Issue by atakantepe** [primefaces/primevue-tailwind#135]

**Comment by AnthonyRuelle** [comment]
+1 ! 

I was just writing a bug on this subject, it only works on the text and I saw that it was not managed in the context
Not working for many inputs (InputNumber, Password, Dropdown, Textarea, Calendar, ..)

**Comment by frasza** [comment]
Is this issue related to the context of components? Asking because I am trying to style based on `context.selected` for `Calendar` component, and it seems like property does not exist.
