### ISSUE TITLE
Invalid states not working on some componentes

### ISSUE THREAD

**Issue by slaven-ii** [primefaces/primevue-tailwind#14]
Hi,

On AutoComplete, Calendar, Chips, inputSwitch, inputTest in the documentation it says to use p-invalid for the invalid state, but that's not working (as it can be noticed in the documentation itself)

For Dropdown it says to use p-invalid but in the example are tailwind classes:  !border !border-red-300 !dark:border-red-400 w-full md:w-14rem

On some components suggested approach is to use p-invalid while on others (that have proper working examples) it's being done with multiple classes. What should be the proper approach?

As we have themes I would expect that the invalid states are part of the theme and they don't need to be custom-written every time. Maybe there can be an example of how to write our own invalid style

**Comment by alfonsovgs** [comment]
Hey @slaven-ii 👋

I agree that the documentation is a bit confusing, but I think the current approach is like this [Extracting classes with @apply](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply) . I'm currently using that, for example for p-invalid or router-link-active.

**Comment by atakantepe** [comment]
Hi, yes, the invalid demos are confusing. We will make them like the disabled, so in the preset, you will be able to give your classes for invalid. This needs changes in the PrimeVue core (PT). We will remove the invalid demos for now. We plan to add this as soon as possible.

**Comment by slaven-ii** [comment]
@alfonsovgs Thanks, with the plans that @atakantepe explained this does look like a good solution for now. Thanks both
