### ISSUE TITLE
Dialog component causing error in console when moved

### ISSUE THREAD

**Issue by GhostvOne** [primefaces/primevue-tailwind#143]
Dialog component causing error in console when moved
You can reproduce it on official page https://tailwind.primevue.org/dialog/

![image](https://github.com/primefaces/primevue-tailwind/assets/798011/c21cc510-bb96-47c4-83c3-19cde96362b6)

**Comment by atakantepe** [comment]
Hi, this might be fixed with the updates on primevue core. I couldn't reproduce it, and since it's been a while, I guessed it is fixed on the primevue core side. If you get this again, please re-open the issue.
