### ISSUE TITLE
Dropdown scroll height cannot be set from preset

### ISSUE THREAD

**Issue by Lehoczky** [primefaces/primevue-tailwind#147]
The [dropdown component](https://tailwind.primevue.org/dropdown/) has a `scroll-height` property, which sets the height of the item list directly on the element. This has higher specificity than setting it from a preset:

![image](https://github.com/primefaces/primevue-tailwind/assets/31937175/75fc52ba-40cc-4c83-8a5b-ae80457217d0)

You can see the default class from the lara preset here: https://github.com/primefaces/primevue-tailwind/blob/main/presets/lara/dropdown/index.js#L105

Since the `scroll-height` property defaults to 200px, it even sets the height when the developer doesn't specify it, overriding the class from the presets. I think the easiest way to "fix" this, is to remove the `max-h-[200px]` from the presets and just always use the `scroll-height` property. A warning about this in the docs would be a nice addition too.

```diff
wrapper: {
        class: [
-            // Sizing
-            'max-h-[200px]',

            // Misc
            'overflow-auto'
        ]
    },
```

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
