### ISSUE TITLE
<Menubar breakpoint="XX"> dont work it uses sm:hidden

### ISSUE THREAD

**Issue by deiiviidas** [primefaces/primevue-tailwind#15]
![image](https://github.com/primefaces/primevue-tailwind/assets/25092057/d07f59b0-70d7-44b6-9f15-1ac3f8b68790)
Menubar breakpoint doest work properly as it should.

**Comment by deiiviidas** [comment]
anyway here is partial fix

`    button: ({ state }) => {
        return {
            class: [
                // Flexbox
                { hidden: !state.queryMatches, flex: state.queryMatches },
....
`

**Comment by mertsincan** [comment]
Thanks a lot for your fix! We'll check and get back to you before the next version is released.

**Comment by atakantepe** [comment]
Hi, we will update our demos for breakpoints. We recommend using responsive utilities of tailwind like sm: md: you can also add custom ones or change the breakpoints. 

https://github.com/primefaces/primevue-tailwind/issues/90

**Comment by pileroniel** [comment]
Hey @atakantepe , just confirming if the demos are updated. It seems the breakpoint prop issue is still persistent
