### ISSUE TITLE
Inconsistent Theming with Lara Presets in Dark Mode

### ISSUE THREAD

**Issue by dicaccamovincenzo92** [primefaces/primevue-tailwind#153]
I've encountered an issue with the Lara presets when using any of the Lara themes, specifically with the lara-dark-amber theme. When the system dark mode is activated, some components display colors that seem to belong to the lara-light-amber theme, and vice versa.

**1. System Dark Mode Activated with lara-dark-amber Theme:**
Some colors appear "reversed"
![image](https://github.com/primefaces/primevue-tailwind/assets/82500275/a1286d5c-eeb4-40d0-a066-fec0d6a11498)

**2. System Dark Mode Activated with lara-light-amber Theme:**
Some colors appear "reversed"
![image](https://github.com/primefaces/primevue-tailwind/assets/82500275/1e1cf0e2-e38e-4fee-aece-66fdd9e5c5ad)

**3. System Light Mode Activated with lara-dark-amber Theme:**
Works as intended
![image](https://github.com/primefaces/primevue-tailwind/assets/82500275/741f61c2-bd03-4ae5-b3c7-260beb2b7548)

Upon investigation, I noticed that the issue might be related to these CSS media queries:

@media (prefers-color-scheme: dark) {
    .dark\:text-surface-0 {
        color: rgb(var(--surface-0));
    }
}

@media (prefers-color-scheme: dark) {
    .dark\:bg-surface-900 {
        background-color: rgb(var(--surface-900));
}

Could I be implementing something incorrectly? Additionally, how can I disable these media queries?

I aim to consistently display the dark theme regardless of my system's theme settings when using lara-dark-amber. What adjustments are needed to achieve this?

I'm attaching these 3 files just to be sure:
app.css:
![image](https://github.com/primefaces/primevue-tailwind/assets/82500275/e6c0a20e-6e0f-43f0-9eef-9acc79d385a0)

tailwind.config.js:
![image](https://github.com/primefaces/primevue-tailwind/assets/82500275/3fb905e5-9d3a-40a2-92b5-0bfa07a1570d)

lara-dark-amber/theme.css:
https://pastebin.com/AFFtZGrr

**Comment by dominikvaradi** [comment]
@dicaccamovincenzo92
My guess is that the `@media (prefers-color-scheme: dark)` thing comes from TailwindCSS itself, it is using selector based dark mode strategy by default. Read more at [Tailwind CSS Dark Mode](https://tailwindcss.com/docs/dark-mode) docs.
First option is to manually set the dark mode strategy to class based, where you have to add `darkMode: 'selector'` to your `tailwind.config.*` file. This way you'll have to manually/programatically switch between light and dark modes.
Second option is to build your whole application around selector based dark mode strategy.

**Comment by atakantepe** [comment]
Hi, you are right. I'll add this to the setup docs. We use "darkMode: 'class'" in the tailwindconfig for the showcase. Thank you for the feedback.🌟

There are lots of places to improve when it comes to showcase & docs, so please give more feedback, also, I suggest the GitHub repo to be the base of information.
