### ISSUE TITLE
Reuse presets for repeated component slots

### ISSUE THREAD

**Issue by robomatic** [primefaces/primevue-tailwind#16]
Currently presets utilize a custom config per component and specific component slots have a completely separate set of classes for their styling. While this is very customizable it would be nice to utilize more reuse throughout the preset. One example is the Chip component. It is used in at least 3 different components under the name `token`, including in the Autocomplete and Chips components preset.

If there could be one chip component with the option to merge and/or override pass-through classes that would reduce code footprint and potential for errors.

**Comment by atakantepe** [comment]
Hi, thank you for your feedback. We actually changed our decision. It was like you asked in our first version, but our primary approach is to make the presets as un-dependent as possible. But I will open this discussion again with the team with your feedback.

**Comment by robomatic** [comment]
Thanks for the response, I can understand that decision. It's a minor optimization with trade-offs. Keep up the great work on the project!
