### ISSUE TITLE
v0.8.0 DataTable  'string' is not assignable to type 'object' error

### ISSUE THREAD

**Issue by chiarotto** [primefaces/primevue-tailwind#160]
Running 
`> vue-tsc --build --force`
I get the following:

 error TS2322: Type 'string' is not assignable to type 'object'.
                                                                                                                       
34              tableStyle="min-width: 50rem">                                                                         
                ~~~~~~~~~~                                                                                             
node_modules/primevue/datatable/DataTable.d.ts:1120:5                                                                
1120     tableStyle?: object | undefined;                                                               
             ~~~~~~~~~~                                                                                                
The expected type comes from property 'tableStyle' which is declared here on type 'DataTableProps & VNodeProps & AllowedComponentProps & ComponentCustomProps & Record<string, unknown>' 

But in the docs,( https://tailwind.primevue.org/datatable/ ) the example reports:
`DataTable :value="products" tableStyle="min-width: 50rem"`

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
