### ISSUE TITLE
Paginator End and Start slots are not in the corners

### ISSUE THREAD

**Issue by sergeydus** [primefaces/primevue-tailwind#171]
the following image is from https://tailwind.primevue.org/datatable/#paginator_template
![image](https://github.com/primefaces/primevue-tailwind/assets/29180697/bce2cc8b-817a-4335-a016-77fbdfe9aa36)

https://primevue.org/datatable/#paginator_template
![image](https://github.com/primefaces/primevue-tailwind/assets/29180697/7371982b-42ad-44d5-afa1-e5cf7c53f3f0)

**Comment by firlottea** [comment]
I personnaly use `mr-auto` and `ml-auto` on each to fix that on my pt as a workaround in case it is helpful

**Comment by sergeydus** [comment]
> I personnaly use `mr-auto` and `ml-auto` on each to fix that on my pt as a workaround in case it is helpful

after your comment I realized was adding margin auto to the button and not the PT, so definitely helped me!

still issue should probably be fixed on their side
