### ISSUE TITLE
DataTable rowexpansioncell passthrough overriding classes instead of adding

### ISSUE THREAD

**Issue by sergeydus** [primefaces/primevue-tailwind#172]
when passing:
`      :pt="{
        rowexpansioncell: 'bg-red-500',
      }"
      :ptOptions="{ mergeSections: true, mergeProps: true }"`
to the dataTable, the rowexpansioncell classes are being overridden instead of added to:

before:
<img width="312" alt="image" src="https://github.com/primefaces/primevue-tailwind/assets/29180697/7c71c8a1-f066-46b8-a83c-c1bcd890340c">
after:
<img width="297" alt="image" src="https://github.com/primefaces/primevue-tailwind/assets/29180697/bdc164bc-b5c5-4fd2-91cb-897633bb9947">

**https://stackblitz.com/edit/ka1dqv?file=src%2FApp.vue**

**Comment by brandon-swipedon** [comment]
> when passing: ` :pt="{ rowexpansioncell: 'bg-red-500', }" :ptOptions="{ mergeSections: true, mergeProps: true }"` to the dataTable, the rowexpansioncell classes are being overridden instead of added to:
> 
> before: <img alt="image" width="312" src="https://private-user-images.githubusercontent.com/29180697/310164373-7c71c8a1-f066-46b8-a83c-c1bcd890340c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzkyMzYsIm5iZiI6MTcwOTY3ODkzNiwicGF0aCI6Ii8yOTE4MDY5Ny8zMTAxNjQzNzMtN2M3MWM4YTEtZjA2Ni00NmI4LWE4M2MtYzFiY2Q4OTAzNDBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIyNDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNTI0NGEyMjU4Y2IxZTZkZDJmMmEwNWExYWY3ZGMwNWUxYWFkNjgwNTNjYzkzMjE4OTE1NjdlNzY3MzEzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UN6N-qheH2MrG7TLOWe7zpKeBH5pUIk5wGdL5KJM6ps"> after: <img alt="image" width="297" src="https://private-user-images.githubusercontent.com/29180697/310164550-bdc164bc-b5c5-4fd2-91cb-897633bb9947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzkyMzYsIm5iZiI6MTcwOTY3ODkzNiwicGF0aCI6Ii8yOTE4MDY5Ny8zMTAxNjQ1NTAtYmRjMTY0YmMtYjVjNS00ZmQyLTkxY2ItODk3NjMzYmI5OTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIyNDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZDI3NDJiYzRjZjE3YzA2NjQxYWEwYjk3YmQ0NTZjMDU5ZjQ5MWE1MTI3YjdjZGNlNThkYmIzMTc4MjljM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.78oYwPGnqWd8WZP3HFtgW0-kXuTN5Qvt7ag4On--vss">
> 
> **https://stackblitz.com/edit/ka1dqv?file=src%2FApp.vue**

The same issue we just discovered when trying to merge the numberinput globally using the usePassThrough composable. I suspect there is a problem when merging class arrays here
[https://stackblitz.com/edit/nhbhmy?file=src%2Fmain.js](https://stackblitz.com/edit/nhbhmy?file=src%2Fmain.js)
