### ISSUE TITLE
Unable to use active menu item

### ISSUE THREAD

**Issue by shubzz2110** [primefaces/primevue-tailwind#174]
`<Menubar :model="menuItems" />`
``const isActive = (path) => {
  return route.path === path
}

const menuItems = ref([
  {
    label: 'Dashboard',
    icon: 'pi pi-home',
    command: () => {
      router.push('/dashboard')
    },
    active: isActive('/dashboard')
  },
  {
    label: 'Calendar',
    icon: 'pi pi-calendar-times',
    command: () => {
      router.push('/calendar')
    },
    active: isActive('/calendar')
  },
  {
    label: 'Rooms',
    icon: 'pi pi-video',
    command: () => {
      router.push('/rooms')
    },
    active: isActive('/rooms')
  },
  {
    label: 'Wallet',
    icon: 'pi pi-wallet',
    command: () => {
      router.push('/wallet')
    },
    active: isActive('/wallet')
  },
  {
    label: 'Messages',
    icon: 'pi pi-comments',
    command: () => {
      router.push('/messages')
    },
    active: isActive('/messages')
  },
  {
    label: 'Settings',
    icon: 'pi pi-sliders-h',
    command: () => {
      router.push('/settings')
    },
    active: isActive('/settings')
  }
])`

// presets/lara/menubar/index.js

`
content: ({ props, context }) => ({
        class: [
            // Shape
            { 'rounded-[15px]': props.root },
            //  Colors
            {
                'text-surface-700 text-sm font-normal dark:text-white/70': !context.focused && !context.active,
                'text-surface-700 text-sm font-normal dark:text-white/70 bg-surface-200 dark:bg-surface-600/90': context.focused && !context.active,
                'text-white dark:text-surface-0/80 bg-primary-900 dark:bg-primary-400/30': context.focused && context.active,
                'text-white dark:text-surface-0/80 bg-primary-900 dark:bg-primary-400/30': !context.focused && context.active
            },

            // Hover States
            {
                'hover:bg-surface-100 dark:hover:bg-surface-600/80': !context.active,
                'hover:bg-primary-500/50 dark:hover:bg-primary-300/30 text-primary-700 dark:text-surface-0/80': context.active
            },

            // Transitions
            'transition-all',
            'duration-200'
        ]
    }),`

I am unable to set menu item active. I have seen in presets to modify active styles like context.active. Can you tell me what wrong I am doing?

**Comment by atakantepe** [comment]
I'll be closing this issue. If you can't find a solution, please add CodeSandbox/Stackblitz and re-open this issue.
