### ISSUE TITLE
Menu component label still takes space if value not provided (Lara theme)

### ISSUE THREAD

**Issue by mbaljeetsingh** [primefaces/primevue-tailwind#183]
This is the menu code I'm using

```
const rowPopupItems = [
  {
    items: [
      {
        label: 'Edit',
        command: () => {
          console.log('Edit')
        },
      },
    ],
  },
];

 <Menu ref="menu" :model="rowPopupItems" :popup="true" />

```

and the output is following, you can see the empty space above the edit even if there is no label for menu

<img width="436" alt="image" src="https://github.com/primefaces/primevue-tailwind/assets/872762/df2fc2fc-cac6-4732-86a9-810e3dcaf3bd">

**Comment by atakantepe** [comment]
The same behavior can also be seen in the Primevue core. If this approach doesn't fix it, you can always reopen this issue. 

have a nice day🌟

**Comment by mbaljeetsingh** [comment]
Thanks @atakantepe 

I didn't read the documentation correctly.
