### ISSUE TITLE
Galleria component not focussing thumbnail

### ISSUE THREAD

**Issue by GhostvOne** [primefaces/primevue-tailwind#192]
the thumbnail on galleria component is not active on tailwind version. Maybe it's a mistake. On initial component, the thumbnail with the same picture is active instead of tailwind version it's always shadowed

![image](https://github.com/primefaces/primevue-tailwind/assets/798011/9c731fca-3840-4f81-9a05-abfb997917be)

**Comment by atakantepe** [comment]
Hi, yes, this is an issue. I need some information to show the active one from primevue core. I'll check with the team if I can't find another way. Currently, I can get the active index but not the item's index, so I can't write a condition for it.

Thank you for letting me know. I'll fix this as soon as possible.
