### ISSUE TITLE
InputText and Dropdown have different text colors

### ISSUE THREAD

**Issue by Stegnerd** [primefaces/primevue-tailwind#195]
Love this work so far! I noticed in my own project that was using the Laura preset that these two components were different text color. I double checked in the docs examples for primevue tailwind, I noticed the that the default text colors are different between these two components in the Presets (at least Lara) as well. I am very new to tailwind so I am not sure if that is intentional and if it is then feel free to close this!

Dropdown is using text-surface-800
![image](https://github.com/primefaces/primevue-tailwind/assets/12737758/a2c21428-76e8-4c6a-b828-e1bfe24a4d83)
[code where I think its being set](https://github.com/primefaces/primevue-tailwind/blob/019861300a4420c4a2b1743dcef2273bf5f399d8/presets/lara/dropdown/index.js#L46)

InputText is using text-surface-600
![image](https://github.com/primefaces/primevue-tailwind/assets/12737758/2af63e63-5c61-49a1-871d-249a08f545b0)
[code where I think its being set](https://github.com/primefaces/primevue-tailwind/blob/019861300a4420c4a2b1743dcef2273bf5f399d8/presets/lara/inputtext/index.js#L25)

**Comment by atakantepe** [comment]
Hi, yes, this is an issue. Thanks for letting me know. I'll check the inputs and the default text colors. I guess this got mixed up when fixing the placeholder issues :D
