### ISSUE TITLE
Button `default` slot is not working correctly with created preset

### ISSUE THREAD

**Issue by skuhnow** [primefaces/primevue-tailwind#2]
This is how my buttons looks like before (styling created with the old theme definition from https://primevue.org/button/
The second one is using the default slot
![grafik](https://github.com/primefaces/primevue-tailwind/assets/2838405/f85b2dd5-b9f6-4141-9f30-e83f5d518cb6)

Now, with a generated preset (Lara) from https://tailwind.primevue.org/builder/ my buttons looks like this (ignore the different colors)
![grafik](https://github.com/primefaces/primevue-tailwind/assets/2838405/ad112735-a43e-4613-bc4e-5c3bbf52c571)

**Comment by atakantepe** [comment]
Hi, can you explain the problem a bit more? Or you can send a Codesandbox because I am not sure about the issue from these screenshots.

Thanks

**Comment by aurelien-cd** [comment]
Hi, I've faced the same issue yesterday, so maybe I can help :
If you try to set the content of the button directly in the slot instead of using the label prop, the button doesn't have the right width (like shown in the picture).

**Comment by skuhnow** [comment]
> Hi, I've faced the same issue yesterday, so maybe I can help : If you try to set the content of the button directly in the slot instead of using the label prop, the button doesn't have the right width (like shown in the picture).

Correct.
But I'm not sure, if/how I can create a Codesandbox with Primevue + Tailwind Preset, but I have the issue with the generated Lara preset from https://tailwind.primevue.org/builder/

**Comment by mertsincan** [comment]
Thanks a lot for your updates! We'll check it before the next version is released.

Best Regards,

**Comment by atakantepe** [comment]
Hi, we will have a catchup release today. I will move this issue to this week's release.
