### ISSUE TITLE
🟢PrimeVue-Tailwind v0.8.x to v0.9.0

### ISSUE THREAD

**Issue by atakantepe** [primefaces/primevue-tailwind#201]
## PrimeVue Tailwind v0.9.0

This is the big update in progress. With this version, some significant changes are on the way
- Aura Preset will be added.
- Wind Preset will be accessible from the Gallery as a community preset. [Github Repo for the Wind Preset](https://github.com/atakantepe/primevue-tailwind-wind) 
- Major refactoring on presets to make it easy to implement. This includes more usage of tailwinds, which "has-" and "peer-" type classes, and less use of "instance.$...".

## PrimeVue Aura Theme/Preset
You can see the styled version on [PrimeVue Showcase](https://primevue.org/)

![for unstyled](https://github.com/primefaces/primevue-tailwind/assets/28745098/80b1fd32-2b70-42fa-b3ca-2303d712de66)

**Comment by atakantepe** [comment]
## Aura Preset

- [ ] Panels Section: Add Panels Section (Aura Preset) #202

**Comment by atakantepe** [comment]
https://github.com/primefaces/primevue-tailwind/issues/135

**Comment by timothymarois** [comment]
@atakantepe is this for primevue 4 or just a new preset? Do we have a plan to update to primevue 4? Appreciate the work you guys are doing!
