### ISSUE TITLE
Paginator breakpoints?

### ISSUE THREAD

**Issue by musiwei** [primefaces/primevue-tailwind#205]
It's written in the API doc but there is no examples. Suggestion: improve the paginator documentation. 

Below shows two paginators on the page. 

```javascript
<Paginator :rows="records.meta.per_page" :totalRecords="records.meta.total"
               :template="{'1024px': 'RowsPerPageDropdown FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink'}"
               currentPageReportTemplate="{first} to {last} of {totalRecords}"></Paginator>
```
![image](https://github.com/primefaces/primevue-tailwind/assets/2687655/e66cd96e-e69e-4ce6-afae-6d51cd2b3f8b)

**Comment by slumtrimpet** [comment]
@musiwei 

I agree the responsive paginator template seems to be broken in unstyled mode.  

I realized this isn't an earth-shattering idea, but we ended up throwing a `computed` field at the paginator template arg with a watcher on the screen width and it works fine (and to me is a bit more 'vuethonic' anyway).

Not sure if they intend 'unstyled' mode to 100% implement the base styled API or not, but it's a workaround for now.

**Comment by atakantepe** [comment]
Hi, unfortunately, the breakpoints are one of the limitations we encounter. The workaround is to customize the breakpoints in the preset to suit your needs. We have plans in the future to improve this but this is more related to primevue core.
