### ISSUE TITLE
`InputNumber` with `FloatLabel` bug

### ISSUE THREAD

**Issue by NamesMT** [primefaces/primevue-tailwind#207]
![image](https://github.com/primefaces/primevue-tailwind/assets/23612546/9b007fbd-ca79-42f1-b2e3-5a1ae22da917)
![image](https://github.com/primefaces/primevue-tailwind/assets/23612546/0bdd1113-f0f1-4b23-b6aa-dd6ddeaf29a9)
When using `FloatLabel`, the label of `InputNumber` doesn't stay floating when there is value.
Works fine with `InputText`

nuxt-primevue: 0.3.1
primevue: 3.50.0

**Comment by Delaylaph** [comment]
I have the same issue with `Password` component. 
primevue: 3.51.0
nuxt-primevue: 0.3.1

**Comment by atakantepe** [comment]
Add Filled State for Inputs [FloatLabel] https://github.com/primefaces/primevue-tailwind/issues/135
