### ISSUE TITLE
Tree: Loading icon on loadingMode is not spinning as supposed

### ISSUE THREAD

**Issue by flaviuskc** [primefaces/primevue-tailwind#208]
Hi guys!

I just wanna report that the loading icon in Lazy loadings using loadingMode='icon' on Tree component is not animated as supposed. 
I had some attempts to fixed locally but nothing concrete.  If someone of the team could take a look at would be great!

I'm attaching an image to find the behavior faster. The icon is exactly as the image below, fixed in that way.
![image](https://github.com/primefaces/primevue-tailwind/assets/87039018/c7a986d0-ccdc-4ff3-ab03-28a51dfabd9a)

**Comment by RedLighttt** [comment]
Hey, 
i have already noticed this with the dropdown component. I added the tailwind class "animate-spin" to the 'loadingIcon' via PassThrough. 
`:pt="{ loadingIcon: 'animate-spin' }"`

You may need to tell the component to merge the properties:
`:pt-options="{ mergeProps: true }"`

You can read more about it here: [https://primevue.org/tree/#pt.doc.tree](https://primevue.org/tree/#pt.doc.tree)

**Comment by atakantepe** [comment]
Hi, this issue will be fixed after the next release of PrimeVue. I need the loading status information to update the preset.

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
