### ISSUE TITLE
Wrong severity check

### ISSUE THREAD

**Issue by Caarnus** [primefaces/primevue-tailwind#214]
### Repository URL

https://github.com/primefaces/primevue-tailwind/blob/main/presets/wind/splitbutton/index.js

**Comment by Caarnus** [comment]
In the splitbutton Wind preset there is a check for secondary on lines 84 and 272 instead of for success:

`
// Success Text Button
{ 'text-surface-500 dark:text-surface-400': parent.props.text && parent.props.severity === 'secondary' && !parent.props.plain },

// Success Text Button
{ 'text-surface-500 dark:text-surface-400': parent.props.text && parent.props.severity === 'secondary' && !parent.props.plain },
`

**Comment by Caarnus** [comment]
Create PR #215 to address

**Comment by atakantepe** [comment]
Thank you for your PR, but the Wind preset is no longer part of the official presets. It has been replaced with the Aura Preset. 

You can add this PR and the issue to the [Wind Preset Github repo](https://github.com/atakantepe/primevue-tailwind-wind). I would be happy to merge it.


❗Wind Preset has been moved (w/ v0.9.0)❗ #242
