### ISSUE TITLE
FloatLabel: Tailwind styles do not play well with LastPass Password manager

### ISSUE THREAD

**Issue by KnightYoshi** [primefaces/primevue-tailwind#224]
LastPass injects its own elements into the page which interferes with expected behaviors with the Tailwind approach

<img width="1113" alt="image" src="https://github.com/primefaces/primevue/assets/6134576/2311379a-bb98-4548-9a07-627bb4249651">
<img width="829" alt="image" src="https://github.com/primefaces/primevue/assets/6134576/85359a55-6655-47c6-8757-4c7c4288c591">

Changing it to target labels specifically works as expected. However, I'm not sure this is the ideal approach. Maybe a specific class would be better, that way it can still be any element that can be used as a label?
```
export default {
    root: {
        class: [
            'block relative',

            // Base Label Appearance
            '[&>label]:text-surface-900/60 dark:[&>label]:text-white/60',
            '[&>label]:absolute',
            '[&>label]:top-1/2',
            '[&>label]:-translate-y-1/2',
            '[&>label]:left-3',
            '[&>label]:pointer-events-none',
            '[&>label]:transition-all',
            '[&>label]:duration-200',
            '[&>label]:ease',

            // Focus Label Appearance
            '[&>label]:has-[:focus]:-top-3',
            '[&>label]:has-[:focus]:text-sm',

            // Filled Input Label Appearance
            '[&>label]:has-[.filled]:-top-3',
            '[&>label]:has-[.filled]:text-sm'
        ]
    }
};
```

**Comment by atakantepe** [comment]
https://github.com/primefaces/primevue-tailwind/issues/135
