### ISSUE TITLE
Updating icons template in panel messes up the header padding (Lara theme)

### ISSUE THREAD

**Issue by mbaljeetsingh** [primefaces/primevue-tailwind#230]
```

<Panel header="Settings">
  <template #icons>
    <Button label="Edit"></Button>
  </template>
  Content
</Panel>
```

![image](https://github.com/primefaces/primevue-tailwind/assets/872762/a9f38d1a-540d-4e9c-b0d3-18af9efbacc5)

**Comment by atakantepe** [comment]
Hi, I suggest checking this demo. It fits your request. The padding and button height are causing this, so the best way is to add a custom header.

https://primevue.org/panel/#template
