### ISSUE TITLE
Password Component must have different size

### ISSUE THREAD

**Issue by pauliverson-mm** [primefaces/primevue-tailwind#233]
Here i am creating a login form my problem is that the size for the password component cannot change just like the inputText component. i hope you can add an option like that in other form fields as well. thanks.

here is the sample of my code:

`      <form action="#" class="bg-white">

        <div class="flex flex-col gap-2">
            <label for="username">Username</label>

                <span class="relative">
                <i class="pi pi-search absolute top-2/4 -mt-2 left-3 text-surface-400 dark:text-surface-600" />
                <InputText v-model="username" size="small" id="username" placeholder="juan.delacruz" aria-describedby="username-help" class="pl-10 w-full" />
            </span>
            <small id="username-help">Enter your username to reset your password.</small>
        </div>

        <div class="flex flex-col gap-2">
            <label for="password">Password</label>

                <span class="relative">
                <i class="pi pi-search absolute top-2/4 -mt-2 left-3 text-surface-400 dark:text-surface-600" />
                <Password v-model="password" size="small"  id="password" toggleMask aria-describedby="password-help" class="w-full" />
            </span>
            <small id="password-help">Enter your password to reset your password.</small>
        </div>
        

      </form>`

i add size="small" but the size of the password field is the same as default. thanks again.

**Comment by atakantepe** [comment]
Hi, password features are coming from the PrimeVue core. You can open a feature request in the primevue repo. Also, You can adjust your preset or add classes, which you can get from the InputText preset


```
  {
      'px-4 py-4': props.size == 'large',
      'px-2 py-2': props.size == 'small',
      'p-3': props.size == null
  },
```
