### ISSUE TITLE
Cannot run repo locally: "Pre-transform error: Failed to resolve import "C:DevGithubpublicprimefacesprimevue-tailwindpresetslara" from "virtual:nuxt:C:/Dev/Github/public/primefaces/primevue-tailwind/.nuxt/primevue-plugin.mjs". Does the file exist?"

### ISSUE THREAD

**Issue by OliverRC** [primefaces/primevue-tailwind#235]
I have tried to run the repo locally to see if I cannot help address another issue I am facing.
https://github.com/primefaces/primevue/issues/5650

However, running `npm run dev` throws the following error:
```
Pre-transform error: Failed to resolve import "C:DevGithubpublicprimefacesprimevue-tailwindpresetslara" from "virtual:nuxt:C:/Dev/Github/public/primefaces/primevue-tailwind/.nuxt/primevue-plugin.mjs". Does the file exist?
```

I've tried Node 18 and 20, and I"ve tried updating Nuxt too but the same result

**Comment by atakantepe** [comment]
Hi, this error is from the nuxt.config.js
If you are using Windows, you need to change the importPT like this:

`importPT: { as: 'Lara', from: '~/presets/lara' }`

**Comment by andreLuis1506** [comment]
I have this issue, but with importTheme
