### ISSUE TITLE
AutoComplete (Multiple Mode): Missing Focus for Token

### ISSUE THREAD

**Issue by strobh** [primefaces/primevue-tailwind#236]
In the AutoComplete component in multiple mode, individual tokens can be focused using the arrow keys on the keyboard and then deleted using the backspace key.

In **styled mode**, the focus on the token is displayed by a different background color (class `p-focus` on the token element):

<img width="1117" alt="Bildschirmfoto 2024-04-30 um 14 14 05" src="https://github.com/primefaces/primevue-tailwind/assets/1754883/e29d570b-3b55-4b70-91f6-e8b75d7552b7">

In **unstyled mode**, however, the focus is not displayed. The accessibility attribute `aria-activedescendant` shows that the first token is selected (and deleting the token also works correctly).

Expected behavior: The focused token should be displayed differently than unfocused tokens like in styled mode.

<img width="1118" alt="Bildschirmfoto 2024-04-30 um 14 30 15" src="https://github.com/primefaces/primevue-tailwind/assets/1754883/30a33fed-0755-4163-a0f4-685680665274">

The focus style would be easy to implement if one had the information about whether the current token has the focus or not, something like:

```
autocomplete: {
    token: ({ tokenState }) => ({
        class: [
            {
                'bg-surface-200',: !tokenState.focused,
                'bg-surface-300': tokenState.focused,
            }
        ]
    }),
```

Unfortunately, the only information provided by PrimeVue is the index of the focused token (`state.focusedMultipleOptionIndex`). Dynamically creating a matching tailwind class using `:nth-child` (e.g., `'[&:nth-child(' + state.focusedMultipleOptionIndex + ')]':bg-surface-300`) is not a real solution (and dynamically created classes are not recognized and included in the production CSS by Tailwind).

**Comment by atakantepe** [comment]
Hi, it seems this changed in the Primevue core, and no more; it gets the focus like that. You can open this in primevue repo. To be able to add this in primevue-tailwind, I need the focus info, which is not available at the moment.
