### ISSUE TITLE
Incorrect rendering of tooltip

### ISSUE THREAD

**Issue by Florian-Mt** [primefaces/primevue-tailwind#238]
Hello,

Workin with tooltips with the laura preset, I encountered two issues.

When a tooltip renders. the external shadow is a few pixels farther than the actual content box on vertical or horizontal axis depending on the tooltip's position. It is due to the CSS having:
```javascript
    root: ({ context, props }) => ({
        class: [ 'shadow-md' ],
    }),
```

But the `shadow-md` class should better be on the `text` item, not `root`.

Secondly, when the tooltip cannot render where it should, it changes position, but the arrow still renders depending on the intended position, i.e. the position where the tooltip is actually not.

I did not find how to fix it, but I bet this part is wrong :
```javascript
    arrow: ({ context, props }) => ({
        class: [
            {
                'border-y-[0.25rem] border-r-[0.25rem] border-l-0 border-r-surface-600': context?.right || (!context?.right && !context?.left && !context?.top && !context?.bottom),
                'border-y-[0.25rem] border-l-[0.25rem] border-r-0 border-l-surface-600': context?.left,
                'border-x-[0.25rem] border-t-[0.25rem] border-b-0 border-t-surface-600': context?.top,
                'border-x-[0.25rem] border-b-[0.25rem] border-t-0 border-b-surface-600': context?.bottom
            },
        ]
    }),
```
In that `context.left | right | bottom | top` seems to be the intended position but not the actual rendering position, but styles should depend on the actual position.

**Comment by jhillacre** [comment]
Seeing this. Regarding the arrow not flipping around, the issue is the context is only passed if on the directive. So `v-tooltip.bottom="test"`, always passes `context.bottom` as true, even when forced to render another way.

It seems like a primevue bug rather than primevue-tailwind, as nothing in the args to the `arrow` function indicates the true position.

**Comment by jhillacre** [comment]
I opened a primevue issue related to this issue:
https://github.com/primefaces/primevue/issues/6095
