### ISSUE TITLE
DynamicDialog emit event

### ISSUE THREAD

**Issue by Ben-Avrahami** [primefaces/primevue-tailwind#240]
the dynamic dialog emit event is not working for me
i tried the example in the documentation and seems like it isnt working eithar.
https://tailwind.primevue.org/dynamicdialog/#events

im emmiting an event in the dialog and created a function in the same name of the emmited event, as in the documentation and the event is not caught. 
whold appricate your help with that.

edit: only the default onClose event seems to be working. other emmited events dont work properly.

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
