### ISSUE TITLE
Inconsistent InputGroup Wind preset

### ISSUE THREAD

**Issue by nielsvanrijn** [primefaces/primevue-tailwind#241]
the `InputGroup` has Inconsistent ring style when focusing and using the Wind preset.
As seen on https://tailwind.primevue.org/inputgroup/

This example has no ring on focus:
![image](https://github.com/primefaces/primevue-tailwind/assets/14902873/322ba313-5364-4e63-a328-cff14cfacedf)

But this has (also it has a rounded ring but it should not be rounded):
![image](https://github.com/primefaces/primevue-tailwind/assets/14902873/b7b6d1a8-bece-40e0-a072-388221dc907c)

**Comment by atakantepe** [comment]
Hi, the wind preset will be replaced after 0.9.0 is released on Monday. Wind is now a community preset and is available on the gallery page. 

I am closing this issue, but you can open it here on the Wind preset repo. [Wind Preset Github repo](https://github.com/atakantepe/primevue-tailwind-wind)

❗Wind Preset has been moved (w/ v0.9.0)❗ #242
