### ISSUE TITLE
Are the code snippets available?

### ISSUE THREAD

**Issue by shakhrillodev** [primefaces/primevue-tailwind#243]
Hi I am a beginner programmer and when I write attribute in component it is not automatically filling the rest? I am using tailwind prime vue Lara preset. Do I have to configure something in VS Code or install any extension?
[Screencast.webm](https://github.com/primefaces/primevue-tailwind/assets/122384829/03d9dcf2-1604-4fa8-9e6e-6f42f1980a3d)

**Comment by atakantepe** [comment]
Hi, you can use Tailwind IntelliSense to get classes, but this won't work directly in the preset files. We will have a solution for this in the future.
