### ISSUE TITLE
Datatable reorder missing visual indicator while dragging (different behavior than styled mode)

### ISSUE THREAD

**Issue by guilheb** [primefaces/primevue-tailwind#253]
When dragging a row in styled mode, there is a visual indicator to let the user know where the drop will occur, as seen [in the examples in the documentation](https://primevue.org/datatable/#reorder) and in the screenshot below.

![image](https://github.com/primefaces/primevue-tailwind/assets/10275215/44e994aa-4120-43be-b7a1-f35f7257116c)

When doing the same in primevue-tailwind, there is no visual indication where the drop will be, as seen [in the examples in the documentation](https://tailwind.primevue.org/datatable/#reorder) and in the screenshot below.

![image](https://github.com/primefaces/primevue-tailwind/assets/10275215/f561f11d-86b9-4339-9274-5dd33727416b)

**Comment by Loqode** [comment]
Did you end up resolving this? I can't get it to work...
