### ISSUE TITLE
MultiSelect Component broken

### ISSUE THREAD

**Issue by seking01** [primefaces/primevue-tailwind#254]
I am using PrimeVue and Tailwind in my Vue.js app and cannot get the [MultiSelect component](https://tailwind.primevue.org/multiselect/) to work as intended (well, I guess it works, but the CSS is not correct somehow). I just installed a new test project with no CSS whatsoever to make sure I'm not overwriting my styles, but it still looks like this:

![image](https://github.com/primefaces/primevue-tailwind/assets/16341293/18e02819-952c-4f3c-afaf-0ed72fb319ae)

I also tried the [PrimeVue Examples](https://github.com/primefaces/primevue-examples/tree/main) with the same outcome. Can anybody help to get this thing working? Everything else from PrimeVue works like a charm...

**Comment by RonaldCast** [comment]
Hello, I have the same issue, Could you solve it? @seking01

**Comment by RonaldCast** [comment]
I solved it, I had downgrade de version of primevue to @3.46.0

**Comment by atakantepe** [comment]
Hi, this issue has likely been resolved in the latest updates.
If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.
