### ISSUE TITLE
Confirm Dialog cannot be styled and document needs updated

### ISSUE THREAD

**Issue by slumtrimpet** [primefaces/primevue-tailwind#255]
As seen in the documentation example here:
https://tailwind.primevue.org/confirmdialog/#basic

The confirm dialog is in (I think) pretty broken in its current implementation.

The documentation refers to styles that don't exist in either preset in this project and the overall look needs some attention.  

Not sure how to style it myself either as it seems the underlying guts that are applying styles to this component aren't working properly as I assume we shouldn't be able to see this code in the HTML source.

![Screenshot from 2024-05-10 16-09-05](https://github.com/primefaces/primevue-tailwind/assets/4440932/3b8f7c2c-467a-4bcd-918d-868573b6199d)

**Comment by nawazishali** [comment]
Update regarding this issue. I tried using the :pt option directly on the dialog component and it does work that way, But the preset doesn't have any effect for some properties like icon and message. This issue needs urgent fixing I suspect a lot of components got broken after the Aura them launch. Looks like a rushed release.

More over the unstyled components look way different in the tailwind presets as compared to the styled components. I could probably help look into this bug but can't find contribution document anywhere?

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
