### ISSUE TITLE
Carousel unusable with numVisible options

### ISSUE THREAD

**Issue by GhostvOne** [primefaces/primevue-tailwind#256]
NumVisible is not working and breakpoints too.
In your documentation too, it doesn't work as excepted on responsive version breakpoint: '1400px' should be numVisible: 2 but it doesn't never shown 2 items.
It's always 3 items displayed by default.

Thanks

**Comment by Pixel-Navigators** [comment]
Came here searching for an answer to this, I ended up just adding the classes for numVisible 1-4 in lara/carousel/index.js

For item and itemCloned:

```js
 // Size
 {
    'w-full': props.numVisible === 1 && props.orientation !== 'vertical',
    'w-full md:w-1/2 ': props.numVisible === 2 && props.orientation !== 'vertical',
    'w-full md:w-1/3': props.numVisible === 3 && props.orientation !== 'vertical',
    'w-full md:w-1/4': props.numVisible === 4 && props.orientation !== 'vertical',
    'w-full h-full': props.orientation == 'vertical',
 },
```

If you are using indicators you will still have to set the responsiveOptions to match the slides/indicators up and set the breakpoints to the same px as your tailwind breakpoints:

```js
<Carousel
   :numVisible="2"
   :numScroll="2"
   :responsiveOptions="[
      {
         breakpoint: '768px',
         numVisible: 1,
         numScroll: 1,
      },
   ]">
```

Worked for me until there is a more elegant solution

**Comment by atakantepe** [comment]
Hi, yes, unfortunately, this is one of the limitations we have. But the answer on top is a way you can use it.
https://github.com/primefaces/primevue-tailwind/issues/90
