### ISSUE TITLE
Property 'showButtons' does not exist on type 'InputTextProps'.

### ISSUE THREAD

**Issue by stefan-kozak** [primefaces/primevue-tailwind#258]
Hey guys, i am typing props for InputText like this:
`
root: ({
        props, context, parent,
    }: InputTextPassThroughMethodOptions)
`

typescript is telling me there is no property **showButtons** on type **InputTextProps** but in documentation pass trough (both presets)

[Link to docs](https://tailwind.primevue.org/inputtext/#presets.lara)
` { 'first:ml-0 -ml-px': parent.instance.$name == 'InputGroup' && !props.showButtons },`

there is mistake in docs or am i using it wrong?

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
