### ISSUE TITLE
Change every color occurrence in a single component

### ISSUE THREAD

**Issue by fhnaumann** [primefaces/primevue-tailwind#260]
I am using a MultiSelect component and I want to change the primary color from the green to red. As far as I understood primevue-tailwind, this is achievable by providing passthroughs. However, this seems cumbersome for such a small change, as I have to manually provide passthroughs pretty much everywhere in the component.
Is there an easy way to override a color variable without modyfing the base css? I want to be able to apply color changes differently for different instances of the same component throughout my app.
To illustrate, I'm looking for something like this:
```vue
<!-- I know no such attribute exists, but maybe something similar is possible -->
<MulitSelect primary="bg-red-200" primary-hover="bg-red-100" ... >

</MultiSelect>
```

**Comment by atakantepe** [comment]
Hi, this is related to the core, but you can open a feature request for this in the primevue repo.
