### ISSUE TITLE
New Row Add

### ISSUE THREAD

**Issue by fwt-parth-jariwala** [primefaces/primevue-tailwind#261]
I have integrated primevue with vue3 + vit in my project.
Now i want to integrate functionality that way that if i press tab on last cell of last row, new empty row should be initialised and when i press escape key it should be cancel adding row.

How do i achieve this?

**Comment by atakantepe** [comment]
You might want to ask this in discussions or on our Discord server. Since this is not related to the project itself, I'll be closing this issue.
