### ISSUE TITLE
MultiSelect with FloatLabel broken

### ISSUE THREAD

**Issue by B0G3** [primefaces/primevue-tailwind#266]
Similiar to #207 
When using **FloatLabel**, the label of **MultiSelect** doesn't stay floating when there is value.
![obraz](https://github.com/primefaces/primevue-tailwind/assets/61941685/3ff83ce4-d875-4e0b-96c7-014c04ec742d)
It also shows "empty" if placeholder isn't set.
![obraz](https://github.com/primefaces/primevue-tailwind/assets/61941685/49e80801-533a-4dd5-9be3-311e383646b4)

![obraz](https://github.com/primefaces/primevue-tailwind/assets/61941685/4ceb39c2-047a-4b30-ae18-6facfbe33b45)

primevue: 3.52.0
vite: 5.2.11

**Comment by catalinp2004** [comment]
have the same issue here. Floatlabel is not floating when Multiselect has selected values.

**Comment by Angel892** [comment]
I have same issue :(
