### ISSUE TITLE
Change Font Size of Calendar Component

### ISSUE THREAD

**Issue by suyovj** [primefaces/primevue-tailwind#270]
Is there a way to change font size (or class) of calendar component. Adding classes to **panelClass** is not overriding **text-base** class in `<table>` tab.

Help/suggestions appreciated...

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
