### ISSUE TITLE
Separator is not working with the menu

### ISSUE THREAD

**Issue by mbaljeetsingh** [primefaces/primevue-tailwind#274]
I'm trying to add separator to the menu item. But, it doesn't seem to work. I'm using the official example.

`const items = ref([
    {
        separator: true
    },
    {
        label: 'Documents',
        items: [
            {
                label: 'New',
                icon: 'pi pi-plus',
                shortcut: '⌘+N'
            },
            {
                label: 'Search',
                icon: 'pi pi-search',
                shortcut: '⌘+S'
            }
        ]
    },
    {
        label: 'Profile',
        items: [
            {
                label: 'Settings',
                icon: 'pi pi-cog',
                shortcut: '⌘+O'
            },
            {
                label: 'Messages',
                icon: 'pi pi-inbox',
                badge: 2
            },
            {
                label: 'Logout',
                icon: 'pi pi-sign-out',
                shortcut: '⌘+Q'
            }
        ]
    },
    {
        separator: true
    }
]);
`
`<Menu :model="items"/>`
![image](https://github.com/primefaces/primevue-tailwind/assets/872762/a89d4cee-896d-4fed-ae59-37a625c928b8)

**Comment by timothymarois** [comment]
I also came across this today. This needs to be PRed into the menu preset with 

```
separator: {
        class: [
            // border
            'my-1 border-t border-surface-200 dark:border-surface-700'
        ]
    },
```

solves the issue

**Comment by mbaljeetsingh** [comment]
Thanks @timothymarois 

This should do until the presets are updated by the team

**Comment by geminigeek** [comment]
same issue
