### ISSUE TITLE
ESLint Duplicate key errors

### ISSUE THREAD

**Issue by tomvo** [primefaces/primevue-tailwind#280]
hi there, it seems ESLint is giving a me duplicate key warnings for these cases:

```
                'text-surface-700 dark:text-white/80': !context.focused && !context.selected,
                'bg-surface-200 dark:bg-surface-600/60': context.focused && !context.selected,
                'text-surface-700 dark:text-white/80': context.focused && !context.selected,
```

this is found is most components (dropdown/listbox, etc). Should I just have eslint ignore this or what is your suggestion here?

**Comment by atakantepe** [comment]
Hi, this issue has likely been resolved in the latest updates.
If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.
