### ISSUE TITLE
Megamenu bug

### ISSUE THREAD

**Issue by ChillyLife11** [primefaces/primevue-tailwind#284]
Hi
There is a bug in the demonstration of the megamenu component's Template section
https://tailwind.primevue.org/megamenu/#template

**Bug's demonstration**
https://github.com/primefaces/primevue-tailwind/assets/91256771/5ce8d817-dfdc-4747-a8a0-a325b0b178a1

Browser: Firefox Browser 126.0.1 (64-bit)
OS: Windows 11 Pro 22H2

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
