### ISSUE TITLE
Button groups dont work with these presets. 

### ISSUE THREAD

**Issue by timothymarois** [primefaces/primevue-tailwind#285]
### Repository URL

https://tailwind.primevue.org/button/#buttonset

Should work with the `<ButtonGroup>` component. Unless this is related to primevue 4. but there is no handle on button groups yet. 

https://primevue.org/button/#buttongroup

**Comment by timothymarois** [comment]
Looks like the tailwind presets dont have the update for button groups. You cant do it yet until it has been updated. 

You should not do groups because of button rounding, you should just do 

`<div class="flex space-x-2 items-center">`

instead of `<span class="p-buttonset">` (this is not a solution to buttons groups)

**Comment by timothymarois** [comment]
There is an unofficial documentation that I see in presets, if you use `<InputGroup>` it gives you the effect of ButtonGroup

**Comment by atakantepe** [comment]
Hi, this issue has likely been resolved in the latest updates.
If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.
