### ISSUE TITLE
Lara: button "icon only" do not work with loading state

### ISSUE THREAD

**Issue by timothymarois** [primefaces/primevue-tailwind#286]
### Repository URL

https://tailwind.primevue.org/button/#icons

https://tailwind.primevue.org/button/#loading

Icon only button, no loader

```
<Button  icon="pi pi-trash" size="small" :loading="true" />
```

Loading with label: 

![Screenshot 2024-06-25 at 4 34 51 PM](https://github.com/primefaces/primevue-tailwind/assets/2489333/c5ea89c3-aa9d-4713-b442-5f329230b2a3)

Loading without label:

![Screenshot 2024-06-25 at 4 34 59 PM](https://github.com/primefaces/primevue-tailwind/assets/2489333/0d8c322b-c038-45e8-96d9-38f54a399f14)

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
