### ISSUE TITLE
TabView - black border appearing when tab is clicked

### ISSUE THREAD

**Issue by ReljaMihajlovic** [primefaces/primevue-tailwind#287]
https://tailwind.primevue.org/tabview/#basic
![image](https://github.com/primefaces/primevue-tailwind/assets/117942125/4222cdf9-22b0-45b4-aa4e-a89bd77d3c5a)

**Comment by atakantepe** [comment]
Hi, the issue is now outdated due to changes in the project structure.

If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.
