### ISSUE TITLE
ConfirmDialog - rejectProps and acceptProps Options Missing

### ISSUE THREAD

**Issue by jinyongp** [primefaces/primevue-tailwind#288]
In the `confirm.require` function in ConfirmDialog, `rejectProps` and `acceptProps` are missing, even though the documentation mentions them. They seem to be replaced by acceptLabel and acceptClass, but this change makes it impossible to set severity. The interface should match the PrimeVue ([ref](https://github.com/primefaces/primevue/blob/8f1952d1f0a0bc39490fef121fbd1650f8ab1379/packages/primevue/src/confirmationoptions/ConfirmationOptions.d.ts#L93)).

```ts
const confirm = useConfirm()

confirm.require({
  message: 'Are you sure you want to proceed?',
  header: 'Confirmation',
  icon: 'pi pi-exclamation-triangle',
  rejectProps: { // Object literal may only specify known properties, and 'rejectProps' does not exist in type 'ConfirmationOptions'.ts-plugin(2353)
    label: 'Cancel',
    severity: 'secondary',
    outlined: true,
  },
  acceptProps: {
    label: 'Save',
  },
  accept: () => {
    toast.add({ severity: 'info', summary: 'Confirmed', detail: 'You have accepted', life: 3000 })
  },
  reject: () => {
    toast.add({ severity: 'error', summary: 'Rejected', detail: 'You have rejected', life: 3000 })
  },
})
```

**Comment by aDogCalledSpot** [comment]
This appears to be fixed in v4

**Comment by jinyongp** [comment]
Thank you for letting me know.
