### ISSUE TITLE
A way to remove unused components from the bundle

### ISSUE THREAD

**Issue by alexey-yarmosh** [primefaces/primevue-tailwind#289]
Hey, I am running `nuxt build` or `nuxt generate` and reviewing output files I was able to find styles for every component (even if it was not used). The only way to get rid of them for now is to manually comment out unnecessary components from `presets/aura/index.js`. Maybe there is a more elegant/automated solution for that?

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
