### ISSUE TITLE
Menubar multi-level hover highlight issue

### ISSUE THREAD

**Issue by fallenfreq** [primefaces/primevue-tailwind#295]
On mobile, when you hover on the nth item inside a multi level menu item, the top level menu item of the same number is incorrectly highlighted too when it shouldn't be highlighted at all. This is also visible at https://tailwind.primevue.org/menubar/ as well as in my own code.

You can see bellow that the second submenu item is selected (Blocks) and so the second menu item (Features) in general is also being highlighted. If "Components" was highlighted, then "Home" would have been, if "Templates" was highlighted, then "Contact" would have been.
<img width="453" alt="Screenshot 2024-07-15 at 16 04 50" src="https://github.com/user-attachments/assets/f9d414b0-08d1-4633-9e86-62f486cff48e">

**Comment by atakantepe** [comment]
Hi, this issue has likely been resolved in the latest updates.
If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.
