### ISSUE TITLE
Lara theme does not have invalid prop style

### ISSUE THREAD

**Issue by sergeydus** [primefaces/primevue-tailwind#297]
on the official docs of the dropdown component, the Invalid prop does nothing when the user uses the 'Lara' theme
https://tailwind.primevue.org/dropdown/#invalid

https://stackblitz.com/run?file=src%2FApp.vue

how it looks: (lara theme)
![image](https://github.com/user-attachments/assets/7da4d33a-6e8f-4f82-96e8-ae5c8b767542)

how its supposed to look like 
![image](https://github.com/user-attachments/assets/2275b0d8-0702-4427-b8e5-30fc4329358d)

**Comment by hiepeng** [comment]
why?
