### ISSUE TITLE
IconField Icons Positioned Outside Inputs, Both Presets

### ISSUE THREAD

**Issue by thomashibbard** [primefaces/primevue-tailwind#298]
Not sure how this is working on the IconField component page itself, however both my local attempts and the StackBlitz linked from the component page, the icon is outside the text input itself

This happens on both Laura and Aura presets:

From the StackBlitz (is):
<img width="586" alt="icon-placement" src="https://github.com/user-attachments/assets/9fa87e4b-0de8-4dcd-a2cc-87481da6ccd2">

From the docs (should be):
<img width="711" alt="icon-placement-stated" src="https://github.com/user-attachments/assets/20d52e4a-8219-4112-b63d-3331673ae397">

Reproduction: https://stackblitz.com/run?file=src%2FApp.vue

**Comment by atakantepe** [comment]
Hi, the reproducer link is not opening, but it shouldn't be an issue if you imported the components correctly. If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.

**Comment by rackycz** [comment]
I had the same problem. The documentation does not tell you that you need to import many dependencies from NPM. I am using VueJS3 and I needed to do this:

install:

```
npm install @primeuix/themes
npm install primeflex // The secret dependency !!
npm install primeicons
npm install primevue
```

main.js:

```
import 'primeicons/primeicons.css'
import 'primeflex/primeflex.css'; // The secret dependency !!
import PrimeVue from 'primevue/config';
import Aura from '@primeuix/themes/aura';
app.use(PrimeVue, {
    theme: {
        preset: Aura
    }
});
```

component.vue

```
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import {FilterMatchMode} from '@primevue/core/api';
import InputText from 'primevue/inputtext';
import IconField from 'primevue/iconfield';
import InputIcon from 'primevue/inputicon';
```

Sadly, the "support" does not answer in detail. They should link all documentations that are necessary instead of closing the ticket.

The resulting code was:

```
<template #header>
  <div class="flex justify-content-center">
    <IconField>
      <InputIcon class="pi pi-search"/>
      <InputText v-model="filters['global'].value" placeholder="Keyword Search"/>
    </IconField>
  </div>
</template>
```
