### ISSUE TITLE
Presets updated for PrimeVue version 4

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primevue-tailwind#299]

**Comment by ludwig-loth** [comment]
Sorry, but where can I find the old presets docs? 
You can't expect everyone to update their application immediately.

**Comment by atakantepe** [comment]
Hey, if you need to access previous versions of the documentation, you can always run them locally. For instance, if you're looking for a version prior to 4.0, you can find it at https://github.com/primefaces/primevue-tailwind/tree/0.9.2. 

As this is an extra project for PrimeVue, we don't have the versioned documentation available. 👍

**Comment by timyourivh** [comment]
It appears that the 4.0 version is not live available yet at https://tailwind.primevue.org/builder/
I noticed files for a couple component files were missing

**Comment by slavco86** [comment]
Atrocious change management from PrimeTek team. This shows - PrimeTek is 100% NOT commercially ready team and product. This is disastrous! 
NEVER EVER AGAIN - I will choose any product made by PrimeTek in future
