### ISSUE TITLE
How do I use this without downloading the preset manually?

### ISSUE THREAD

**Issue by 0blu** [primefaces/primevue-tailwind#3]
How do I use PrimeVue-Tailwind, without downloading the preset zip manually and adding it to my project?
Is there an npm repo or something?

**Comment by skuhnow** [comment]
There is no repo for the presets, the are supposed to be a starting point for your own theme. See also this message from the official discord server: https://discord.com/channels/787967399105134612/787968875135762452/1184211041652047952

**Comment by atakantepe** [comment]
Hi, you can download it from the builder, or you can download it from here: https://github.com/primefaces/primevue-tailwind/releases/tag/0.1.0. We dont have an npm package for this because our recommendation to use presets is actually copy and paste. You can easily add whatever you want if you have made customizations. 

We will be adding other components incrementally. Our plan is to release every Wednesday.

**Comment by cagataycivici** [comment]
You can do it with usePassThrough which is able to import a Preset and lets you customize with merge strategies, I'll write up a doc for this but I don't recommend this approach, idea is to have the styles fully customizable in your app rather than import and override.

**Comment by deiiviidas** [comment]
could you make it a little bit smarter ? for example. whenever i use simple Button, default, with label only. javascript bundles all possible button variations, and uses a lot of lines of code, which is not used anywhere it just bundles it and sits there, for no reason.

for example.

![image](https://github.com/primefaces/primevue-tailwind/assets/25092057/73651b7e-3bd3-4cb8-91cc-9b01f02aeb02)

**Comment by deiiviidas** [comment]
also button module from presets generated additional 240kb of types, for button component, which is included also within build bundle.
![image](https://github.com/primefaces/primevue-tailwind/assets/25092057/5cc04fbd-180e-4d52-93a4-cea66fb25fed)

**Comment by mertsincan** [comment]
Hi,

Frankly, it is a little difficult to do this in the short term. For such questions, having a custom component and its preset is the way we recommend. Exp;
```
// your IconOnlyButton.vue
<template>
     <Button :pt={
             // copy preset values related to icon only
     }
<template>
```
Then, don't add a global button preset. If you have any problems regarding this structure, please feel free to ask.
Best Regards,
