### ISSUE TITLE
Missing V4 `FloatLabel` Implementations and Docs

### ISSUE THREAD

**Issue by BenJackGill** [primefaces/primevue-tailwind#303]
For many of the new V4 Tailwind presets the `FloatLabel` feature is either missing from the docs or it doesn't work.

All of these components have the FloatLabel feature available in regular PrimeVue V4 but it is missing from the PrimeVue V4 Tailwind docs:

- [AutoComplete](https://tailwind.primevue.org/autocomplete/)
- [CascadeSelect](https://tailwind.primevue.org/cascadeselect/)
- [DatePicker](https://tailwind.primevue.org/datepicker/)
- [InputMask](https://tailwind.primevue.org/inputmask/)
- [InputNumber](https://primevue.org/inputnumber/)
- [InputText](https://primevue.org/inputtext/)
- [MultiSelect](https://tailwind.primevue.org/multiselect/)
- [TextArea](https://tailwind.primevue.org/textarea/)
- [TreeSelect](https://tailwind.primevue.org/treeselect/)

For many of the above, it is not just a problem of missing documentation. When wrapped with a `<FloatLabel>` they do not display correctly.

**Comment by mpolverini** [comment]
Same problem here!
I'm using DatePicker component with FloatLabel and it does not work: the label is stuck on top of the input.
Also, the documentation is missing.

Any news about this problem resolution?

**Comment by WatCodeDatCode** [comment]
There seem to be multiple reasons for the hidden docs for these components. 

The filled state on some components is not reliable so the FloatLabel can do quick back-and-forth transitions when selecting. See [this PR fix](https://github.com/primefaces/primevue-tailwind/pull/307) that should work for a handful of them.

I just opened [a PR fix](https://github.com/primefaces/primevue-tailwind/pull/313) for the float label transitioning from behind the input on focus which should also solve the problem for most simple input components.

Some components, like DatePicker, will require additional fixes for their respective filled states to work reliably for the FloatLabel though.
