### ISSUE TITLE
Unable to Find v3 InlineMessage Component Preset After Upgrading to v4

### ISSUE THREAD

**Issue by tolgaand** [primefaces/primevue-tailwind#305]
The disorganization of the library is quite frustrating. I need the preset for the InlineMessage component from version 3, but since the upgrade to version 4, I can no longer find it. There seems to be no accessible location for the v3 InlineMessage component. Could you please provide guidance on where I can find the v3 preset or offer any assistance to retrieve it?

**Comment by ekh-anadeainc** [comment]
The latest v3 preset: [Link](https://github.com/primefaces/primevue-tailwind/releases/tag/0.9.2)
The PrimeVue team has removed an InlineMessage in the new version, you can find all the information [here](https://primevue.org/guides/migration/v4/)

**Comment by AnthonyRuelle** [comment]
https://primevue.org/guides/migration/v4/


Deprecated Components => InlineMessage | Use Message component.

**Comment by tolgaand** [comment]
> https://primevue.org/guides/migration/v4/
> 
> Deprecated Components => InlineMessage | Use Message component.

Since it's a large project, migrating to v4 would require more time and cost
