### ISSUE TITLE
Toast - content text get out of the box

### ISSUE THREAD

**Issue by AnthonyRuelle** [primefaces/primevue-tailwind#306]
When a toast has text content that does not have a space, it comes out of the container.

![image](https://github.com/user-attachments/assets/686bcd06-353e-42f1-a89e-072f25dd0f0c)

**Comment by atakantepe** [comment]
Hi, this issue has likely been resolved in the latest updates.
If you're still experiencing the problem, please feel free to reopen the issue or create a new one with more details.
![image](https://github.com/user-attachments/assets/f3a562a3-3105-472d-9bac-6d429c53d3a8)
