### ISSUE TITLE
CofirmDialog styles only apply to the root and transitions

### ISSUE THREAD

**Issue by aDogCalledSpot** [primefaces/primevue-tailwind#308]
I'm using PrimeVue version 4.0.0.

I copied the default lara configuration from [the documentation](https://tailwind.primevue.org/confirmdialog/). The styles for the "root" and "transition" component are being applied but not for any of the other components.

For the following code then:

```ts
const deleteConfirm = () => {
  confirm.require({
    message: 'Are you sure you want to delete this',
    header: 'Confirmation',
    // position: 'top',
    rejectProps: {
      label: 'Cancel',
      severity: 'secondary',
      outlined: true,
    },
    acceptProps: {
      label: 'Delete',
      severity: 'danger',
    },
    accept: () => {
      console.log('deleted')
    },
    reject: () => {
      console.log('canceled')
    },
  })
}
```

The result looks like this:

![image](https://github.com/user-attachments/assets/8a306e2d-9912-4cf4-94d5-c5491c096371)

---

I noticed there is a mismatch between the code in the documentation mentioned above and the code in this repository for the ConfirmDialog. Is this intended?

**Comment by aDogCalledSpot** [comment]
Despite working, the `transition` field also isn't listed in the [`ConfirmDialogPassThroughOptions`](https://github.com/primefaces/primevue/blob/1516d674a4a0299a383724cdbcaf965283e24467/packages/primevue/src/confirmdialog/ConfirmDialog.d.ts#L67) which is unfortunate since I'm using TypeScript for my preset.

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
