### ISSUE TITLE
Can't find the V3 docs for PrimeVue Tailwind

### ISSUE THREAD

**Issue by ludwig-loth** [primefaces/primevue-tailwind#309]
After the shift to v4 I can't find the V3 docs for PrimeVue Tailwind.
Does anyone has a link to it?

Migrating is not an Option at this point (maybe later) because my project has a very big scale and is actually being used.

**Comment by dispatchrabbi** [comment]
I'd like to bump this. I was using the Wind preset and so upgrading to v4 is a huge project for me and so isn't going to happen immediately — especially without a migration guide to ensure I didn't miss anything. So for now, I'm still on v3.

It'd be great to be able to access the v3 docs still. Is there a link to them we're missing?

**Comment by JasperTey** [comment]
I have to agree with everyone here. I started running into blindspots where things on the V4 docs do not apply to V3. The non-tailwind primevue docs have a version switcher at the top right of the page; that would be great on the tailwind docs site. 

## Temporary Solution
In the meantime, here's a solution that seems to work, but involves cloning this repo locally.

Clone the repo, targetting 0.9.2, the latest non-v4 release.
```sh
mkdir primevue-tailwind-v3
cd primevue-tailwind-v3
git clone --branch 0.9.2 git@github.com:primefaces/primevue-tailwind.git .
```

Install npm dependencies
```sh
npm i
```

Build
```sh
npm run dev
```

If all goes well, docs are served locally at http://localhost:3000/

![image](https://github.com/user-attachments/assets/07b5cf06-71c0-48d0-8174-966b2916b6cc)

**Comment by atakantepe** [comment]
Hi @ludwig-loth,
The PrimeVue Tailwind is a side project aligned with PrimeVue's core development, so we don't maintain separate versioned docs for it. However, as @JasperTey suggested, you can clone the v3 repo and run the docs locally to access the older version. The Tailwind preset will continue to follow PrimeVue's updates.

@dispatchrabbi, just to clarify, the Wind preset is separate from the official presets, but I do plan to update it soon. Feel free to reach out if you wanna help: [PrimeVue Tailwind Wind Preset](https://github.com/atakantepe/primevue-tailwind-wind).

Cheers!
