### ISSUE TITLE
ptOptions overrides the defaults of its children

### ISSUE THREAD

**Issue by sergeydus** [primefaces/primevue-tailwind#320]
ptOptions of parent components seem to override the default options of it's child component

expected: the ptOptions of a parent shouldn't affect the styling of the children

Primevue Version: 4.0.5

Firstly, i've overwritten the default ptOptions to be:
`
app.use(PrimeVue, { unstyled: true, pt: Aura, ptOptions:{
  mergeProps: false,
} });`

this is how the following code looks like without ptOptions, the Button behaves as expected:
`     <Panel>
      <Button
        icon="pi pi-arrow-right"
        pt:root="bg-green-500"
        @click="visible = true"
      />
    </Panel>`
![image](https://github.com/user-attachments/assets/b607b55e-b5f4-45cf-880c-31bea7c5f624)

now, if I override the ptOptions in panel, the Buttons style changes, despite the ptOptions being for the Panel component, rather than the Button Component:

`<Panel
      :ptOptions="{
        mergeProps: true,
        mergeSections: true,
      }"
    >
      <Button
        icon="pi pi-arrow-right"
        pt:root="bg-green-500"
        @click="visible = true"
      />
    </Panel>`

which results in:  
![image](https://github.com/user-attachments/assets/2ee40e31-fe9c-44a1-ad04-f8859b738c98)

reproduction: https://stackblitz.com/edit/wf943d?file=src%2FApp.vue
in the reproduction, simply remove/add the ptOptions in panel, and see how it affects the Button's styling

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply instead of pass-through. As a result this issue is not relevant any more.

New Website is [live](https://tailwind.primevue.org).
