### ISSUE TITLE
Icons Spinner doesn't work anymore

### ISSUE THREAD

**Issue by GhostvOne** [primefaces/primevue-tailwind#323]
https://tailwind.primevue.org/icons/#spin
Spinner doesn't work anymore

**Comment by atakantepe** [comment]
Hi, can you provide an example? In the demo, it seems to be working, and it works locally with the latest commits.

**Comment by GhostvOne** [comment]
Did you see them on the doc spining ? On my dev environement it's the same, it's not spining 

![image](https://github.com/user-attachments/assets/1b9ff37d-736e-4f0f-a2cc-c1b00c550f94)

**Comment by atakantepe** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

This is for the users who prefer reduced motion. You can check your preference.

**Comment by GhostvOne** [comment]
Oh , thank you, I've never heard of that before
