### ISSUE TITLE
Could not find a declaration file for module './presets/aura'

### ISSUE THREAD

**Issue by Zyles** [primefaces/primevue-tailwind#325]
Downloaded the presets package and unzipped it.

```
import Aura from './presets/aura'

const app = createApp(App)
  .use(PrimeVue, {
    unstyled: true,
    pt: Aura,
  })
  .use(router)
```

Error:
`Could not find a declaration file for module './presets/aura'`

The styling works but I can not build my project.

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply. This issue should be resolved with the new implementation.

New Website is [live](https://tailwind.primevue.org).
