### ISSUE TITLE
FloatLabel with Textarea is not working as expected

### ISSUE THREAD

**Issue by mpolverini** [primefaces/primevue-tailwind#327]
Hi everyone,
I noticed this bug with FloatLabel used with TextArea:

![image](https://github.com/user-attachments/assets/ba063a5a-f8d3-4705-8df2-37a078ed3a6d)
(screenshot from https://tailwind.primevue.org/textarea/#floatlabel)

the correct behaviour should be:

![image](https://github.com/user-attachments/assets/5b4444bd-77e2-4e45-ab97-2ce3b9beab0a)
(screenshot from https://primevue.org/textarea/#floatlabel)

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply. This issue should be resolved with the new implementation.

New Website is [live](https://tailwind.primevue.org).
