### ISSUE TITLE
FloatLabel + InputNumber with fluid prop not working as expected

### ISSUE THREAD

**Issue by mpolverini** [primefaces/primevue-tailwind#328]
I'm using InputNumber in combination with FloatLabel but when I specify the `fluid ` prop the input does not span 100% of parent width as expected.

stackblitz: https://stackblitz.com/edit/g1wpfk?file=src%2FApp.vue

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply. This issue should be resolved with the new implementation.

New Website is [live](https://tailwind.primevue.org).
