### ISSUE TITLE
Menu passthrough not working

### ISSUE THREAD

**Issue by mpolverini** [primefaces/primevue-tailwind#330]
I'm trying to change the appearance of the Menu component via passtrough, but it doesn't seem to work. 
Specifically when I try to change the color of the text, the specified classes are completely ignored.

Stackblitz: https://stackblitz.com/edit/shdix9?file=src%2FApp.vue

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply. This issue should be resolved with the new implementation.

New Website is [live](https://tailwind.primevue.org).
