### ISSUE TITLE
ProgressSpinner 'spin' property in presets

### ISSUE THREAD

**Issue by MayaSol** [primefaces/primevue-tailwind#332]
There is 'spinner' property in presets for ProgressSpinner. It's classes doesn't apply to element with property data-pc-section="spin".
There must be 'spin' property, not 'spinner'.

![image](https://github.com/user-attachments/assets/b8e82f43-10aa-4c62-92ad-299022f40101)

**Comment by cagataycivici** [comment]
As of v4.1.1, the new Tailwind styles have been rewritten using the [preprocessor](https://tailwindcss.com/docs/using-with-preprocessors) approach with @apply. This issue should be resolved with the new implementation.

New Website is [live](https://tailwind.primevue.org).
