### ISSUE TITLE
Access to advanced options

### ISSUE THREAD

**Issue by frasza** [primefaces/primevue-tailwind#339]
Hey 👋

First of all, thank you very much @cagataycivici for your effort and work on using native CSS with `@apply` for Tailwind, does make a lot of sense.

I would like to know, how could I use advanced login with it, for example styling based on some state.

Personally I have example of Panel component, where I want to style the root of it based on state of `collapsed`. Based with PT, I had logic:
```
{
   'bg-gray-0': state.d_collapsed,
   'bg-gray-50': !state.d_collapsed,
}
```
but here I don't have any `data` or something else to target against. Also, doesn't seem like I can mix `@apply` approach with global PT options?
Any other options?

**Comment by CCodam** [comment]
Agreed, **thank you** so much for your hard work, I'm so excited to start using PrimeVue with Tailwind.

I guess the components will need added logic to either emit, add classes, or add data attributes on state changes?

While we wait for a possible solution in the codebase ...
Some components already somewhat emit state changed, in the case of the Panel component, `update:collapsed` is emitted within the toggle method, but not through a watcher.

That means we can do something like
```vue
<Panel
  header="Header"
  :class="{ 'bg-gray-50': dCollapsed }"
  @update:collapsed="(newVal) => { dCollapsed = newVal }"
  toggleable
>
```

For a solution that'll work for all state changes, we can add our own watcher
https://stackblitz.com/edit/primevue-4-vite-issue-template-qvefuw?file=src%2FApp.vue
- We ref the component
- We set the initial state value and add a watcher for it at `onMounted`.
```vue
<template>
  <Panel header="Header" ref="comPanel" :class="{ 'bg-gray-50': dCollapsed }" toggleable>
    <p class="m-0">
      Lorem ipsum dolor sit amet...
    </p>
  </Panel>
</template>

<script setup>
import { ref, onMounted, watch } from 'vue';

const comPanel = ref();
const dCollapsed = ref();

onMounted(() => {
  dCollapsed.value = comPanel.value.d_collapsed;

  watch(
    () => comPanel.value.d_collapsed,
    (newVal) => { dCollapsed.value = newVal; }
  );
});
</script>
```

**Comment by frasza** [comment]
Its possible to achieve this simply by setting `pt` on components, but I wanna do this globally. In Nuxt, it would be cool if something like this worked.
```
primevue: {
    options: {
      theme: 'none',
      pt: {
        panel: {
          root: ({ state }) => ({
            class: [
              {
                'bg-gray-0': state.d_collapsed,
                'bg-gray-50': !state.d_collapsed,
              },
            ],
          })
        },
      },
    },
    autoImport: true,
  },
  ```

**Comment by CCodam** [comment]
My mistake, I thought pt had been disabled both globally and on the component level when using `theme: 'none'`, and that's why you were reaching out .. **it is not**.
Sorry I assumed, I should have checked first, I've only just had some time to play around with the `theme: 'none'` version of PrimeVue with Tailwind.

_For everyone else with the same question..._
As you said, we can still use the **importPT** setting https://primevue.org/nuxt/#importpt
https://stackblitz.com/edit/nuxt-starter-fkaznd?file=nuxt.config.ts,src%2Fassets%2Fprimevue-tailwindpt.js,app.vue
```js
//nuxt.config.ts
...
primevue: {
  options: {
    theme: 'none',
  },
  importPT: { as: 'TailwindPT', from: '@/src/assets/primevue-tailwindpt.js' },
},
...  
```
```js
//primevue-tailwindpt.js
const TailwindPT = {
  panel: {
    root: (options) => ({
      class: [
        {
          'bg-gray-0': options.state.d_collapsed,
          'bg-gray-200': !options.state.d_collapsed,
        },
      ],
    }),
  },
};

export default TailwindPT;
```
