### ISSUE TITLE
Calendar lost normal state background color when set pt-options mergeProps to true

### ISSUE THREAD

**Issue by caokiet-daydelight** [primefaces/primevue-tailwind#34]
Hi,
Thank you for this wonderful component library. I really like it.

I currently want to customize the Calendar component, but when I change `pt-options` to `{ mergeSections: true, mergeProps: true }` the background color of `todaybutton` and `clearbutton` will be lost.

Do I misunderstand, or is this a bug? Any information would be greatly appreciated.

Here is my custom calendar.

```vue
                            <Calendar
                                v-model="transaction.expectDate"
                                :disabled="!editable"
                                :pt="{
                                       input: {'!ring-red-500': $page.props.errors[`transactions.${index}.expectDate`]}
                                }"
                                :pt-options="{ mergeSections: true, mergeProps: true }"
                                icon-display="input"
                                show-button-bar
                                show-icon
                            />

```

Result:
<img width="374" alt="image" src="https://github.com/primefaces/primevue-tailwind/assets/114906106/b817b452-e093-48f6-8266-2168c9aa3c99">

**Comment by caokiet-daydelight** [comment]
<img width="1562" alt="image" src="https://github.com/primefaces/primevue-tailwind/assets/114906106/c5f3041e-6939-4140-b11f-5b9f8fa321fd">
I found the problem is because when set `mergeProps: true `, clear button and today button also merge props of the normal button, which causes the problem.

**Comment by mertsincan** [comment]
Hi @caokiet-daydelight,

Thanks a lot for your report! Could you please create an issue with a stackblitz sample in PrimeVue Github? We can examine this in more detail.

Best Regards,
