### ISSUE TITLE
Popover arrow renders on the wrong side 

### ISSUE THREAD

**Issue by benkissi** [primefaces/primevue-tailwind#341]
The popover component  `https://tailwind.primevue.org/popover/` renders the arrow on the wrong side. I thought it was something I did wrong and tried it on your documentation example and the behaviour is the same. 

I moved the button in the example to the far right and popover rendered the arrow on the left

https://prnt.sc/iSaPW3nCwQGy

<img width="961" alt="Screenshot 2024-10-29 at 9 44 49 PM" src="https://github.com/user-attachments/assets/d572c1c8-2f38-4774-9e2b-756524d595bb">

**Comment by tugcekucukoglu** [comment]
Cannot replicate the issue. If you think the problem still persists, please reopen this issue with a reproducer link.

**Comment by iduchamp** [comment]
I have the same problem

for fix need to add this code into popover.css

```
.p-popover:after, .p-popover:before {
     left: calc(1.25rem + var(--p-popover-arrow-left))
}
```
cause: on original primevue u have this rule:
```
.p-popover:after, .p-popover:before {
     ......
     left: calc(var(--p-popover-arrow-offset) + var(--p-popover-arrow-left));
     .....
}     

```
and tailwind version css have just 
```
.p-popover:after, .p-popover:before {
      .....
      left: 1.25rem;
      .......
}    
```

**Comment by benkissi** [comment]
Thanks
