### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Sytten** [primefaces/primevue-tailwind#348]
Hi!
Would it be possible to have a changelog for this repository, I get that it is closely tied to primevue versions but it is has it's own bug fixes, etc. The releases in the repo are also not all there, so becomes hard to know if an issue is fixed or not at which version.
Thanks a lot for the hard work

**Comment by tugcekucukoglu** [comment]
Thank you for your suggestion. The changelog will be available with new version.
