### ISSUE TITLE
Badge directive not working

### ISSUE THREAD

**Issue by aeruggiero** [primefaces/primevue-tailwind#35]
When using badge as directive the badge is not correctly shown.

Setup of createApp. Please not that all the import are done correctly and that the preset (GOL) is the default lara preset downloaded from the website. 
   createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue)
            .use(PrimeVue, {
                unstyled: true,
                pt: GoL,
            })
            .use(i18n)
            .directive("ripple", Ripple)
            .directive("badge", BadgeDirective)
            .directive("styleclass", StyleClass)
            .directive("tooltip", Tooltip)
            .use(ToastService)
            .use(DialogService)
            .use(ConfirmationService)
            .mount(el);
            
  <i v-badge="2" class="pi pi-bell relative" style="font-size: 2rem" />
  This renders like:
  
![image](https://github.com/primefaces/primevue-tailwind/assets/68345097/0553945c-bf77-43d4-9dc4-812a20ea319a)

Instead of 
![image](https://github.com/primefaces/primevue-tailwind/assets/68345097/7310e804-d43f-419b-ad07-ea554da2cba6)

**Comment by atakantepe** [comment]
Hi, can you send a Codesandbox so I can see the issue easily?

Thanks.

**Comment by aeruggiero** [comment]
Hi, 
thanks for your answer.

I found the issue actually.

When exporting a preset from the website through the builder, the index.js exports like
export default {
    global,
    directives: {
        tooltip,
         badgedirective,
        ripple,
    },
    ...}
    
    While for the badge to work 
    export default {
    global,
    directives: {
        tooltip,
        badge: badgedirective,
        ripple,
    },...}
    it's needed
