### ISSUE TITLE
Multi Select issue on official documentation

### ISSUE THREAD

**Issue by GhostvOne** [primefaces/primevue-tailwind#359]
There is an issue with multi select. Just go on clear icon section : https://tailwind.primevue.org/multiselect/ 
Select multiple value and unselect them. Clear icon still apearing

![image_2024-11-18_075858593](https://github.com/user-attachments/assets/65d3ef6c-fd79-43ab-90c1-39b2b9aac0f4)

On my dev env same issue but placeholder doesn't appear too until I click on the clear icon (lara pressets)

![image](https://github.com/user-attachments/assets/f8826bf8-1d84-4618-b2a2-18453945582d)

**Comment by tugcekucukoglu** [comment]
Please track: https://github.com/primefaces/primevue-tailwind/issues/369

Thank you!
