### ISSUE TITLE
InputGroupAddon: Button in addon padding

### ISSUE THREAD

**Issue by brecht-vermeersch** [primefaces/primevue-tailwind#362]
```vue
  <InputGroup>
    <InputGroupAddon>
      <Button severity="secondary">btn</Button>
    </InputGroupAddon>
    <InputText />
  </InputGroup>
```

results in
![Screenshot 2024-11-25 at 11 54 17](https://github.com/user-attachments/assets/ed342941-5f83-4760-a8f5-76968e8a8bfd)

This can also be seen on the documentation page: https://primevue.org/inputgroup/#button vs https://tailwind.primevue.org/inputgroup/#button

**Comment by tugcekucukoglu** [comment]
Please create a ticket for PrimeVue. When it is implemented, it will be ported to primevue-tailwind.

Thank you!
