### ISSUE TITLE
TreeSelect Component: clearIcon is not positioned correctly

### ISSUE THREAD

**Issue by simplg** [primefaces/primevue-tailwind#363]
When using the css for the 4.2.3 release, the clearIcon of the TreeSelect component is positioned too far top right (as shown in the screenshot below).

<img width="296" alt="TreeSelect clearIcon" src="https://github.com/user-attachments/assets/f722d7e2-898d-4c18-ade9-2def05a41971">

There is a live example at [Primevue Tailwind Documentation](https://tailwind.primevue.org/treeselect/#clearicon). 

## What should be expected
<img width="316" alt="Correct TreeSelect clearIcon position" src="https://github.com/user-attachments/assets/6c883dc7-f6e0-461a-b3df-d4223ca272b4">

Correct position can be seen at [Primevue Official documentation](https://primevue.org/treeselect/#clearicon).

## Possible Fix
It seems https://github.com/primefaces/primevue-tailwind/blob/main/assets/styles/primevue/treeselect.css is missing this css rule:
```css
.p-treeselect-clear-icon {
  @apply absolute top-1/2 -mt-2 text-surface-500 dark:text-surface-400 end-10;
}
```

**Comment by tugcekucukoglu** [comment]
Please track: https://github.com/primefaces/primevue-tailwind/issues/369

Thank you!
