### ISSUE TITLE
How to set CSS variables of other preset themes

### ISSUE THREAD

**Issue by yuannancheng** [primefaces/primevue-tailwind#365]
According to the official documents and examples, I need to define the CSS variables utilized by the `tailwindcss-primeui`

The official example refers to this file: <https://github.com/primefaces/primevue-examples/blob/main/vite-unstyled-tailwind/src/style.css>

But the example provides the theme color of `emerald`, and I want to change it to the theme color variable of `indigo`.

Is there an official CSS variables file for the `indigo` theme?

Thank you.

**Comment by tugcekucukoglu** [comment]
You can create your own theme, for example:https://primevue.org/theming/styled/#primary
