### ISSUE TITLE
Use scaled spacing for margin and padding

### ISSUE THREAD

**Issue by pwang2** [primefaces/primevue-tailwind#366]
Does it make more sense if we use scaled spacing like px-2, ma-3 as default value instead of arbitrary values here in default tailwind preset?

Rationale is we need customization for spacing in a lot of occasions as the default value for almost all UI elements are deemed as too spacious. Overriding REM value sounds like more intrusive as tailwind theme provided scaled spacing can be customized to as below.

<img src="https://github.com/user-attachments/assets/8860288d-8153-4d2b-950f-faca90c2d0c5"  width="240px"/>

<img src="https://github.com/user-attachments/assets/97c3156e-2a67-4549-8c3a-1f06eafdd45f"  width="320px"/>

**Comment by tugcekucukoglu** [comment]
Thanks for the suggestion. Of course, that's an option, but right now we're aiming for it to work exactly the same as PrimeVue and not require any extra configuration.

Thanks for your understanding.
