### ISSUE TITLE
Components unnecessarily have a white background, preventing out-of-the-box use on non-white pages

### ISSUE THREAD

**Issue by rtroost** [primefaces/primevue-tailwind#368]
I noticed this after switching from the JS-based theme system to the PostCSS system. A lot of components (such as Tabs, TabList, DataTable, etc.) have had a white background added to them. For us, most of the standard styling is fine, with the exception of this as we do not use a #fff background, as I think a lot of users don't. 

I don't think there's any reason for these components to not be transparent and would like to open up the discussion of the possibility of having this default changed going forward.

**Comment by tugcekucukoglu** [comment]
Issue tracker is used for defects only as part of our commitment to quality and continuous improvement in all areas. Enhancements are collected as valuable community feedback and managed internally so moving this enhancement ticket to our internal project management backlog. 

For enhancement requests and other topics, you can open a new topic in [PrimeVue discussions](https://github.com/orgs/primefaces/discussions/categories/primevue).
