### ISSUE TITLE
InputSwitch not styling correctly - missing toggle piece

### ISSUE THREAD

**Issue by nla-sean** [primefaces/primevue-tailwind#4]
Attempting to use the inputSwitch and have updated the theme colours on the tailwind side, but the actual toggle piece is refusing to appear (and I haven't messed with the index file to adjust the styling)

![image](https://github.com/primefaces/primevue-tailwind/assets/153699908/2d43021f-5939-47fd-8bea-8d6d85947bd3)

However, the same colours and no tampering with the index file works fine.

![image](https://github.com/primefaces/primevue-tailwind/assets/153699908/19e66223-979e-450d-8609-b16abdeee105)

Not sure what else may need provided, but happy to if needed.

**Comment by atakantepe** [comment]
Hi, can you check if something is different from this CodeSandbox?
https://codesandbox.io/s/6x55nf?file=/src/App.vue

Also you can send a codesandbox so I can check what is missing.

**Comment by mertsincan** [comment]
Hi,

I have tagged this issue as "Incomplete" for now. If a new update comes from your side, please reopen this ticket. Thanks a lot for your understanding!

Best Regards,
