### ISSUE TITLE
Tooltip: Incorrect Tailwind classes `-m-t-1` and `-m-l-1` in lara preset

### ISSUE THREAD

**Issue by strobh** [primefaces/primevue-tailwind#5]
### Describe the bug

The lara preset for the Tooltip component uses non-existent Tailwind classes `-m-t-1` and `-m-l-1`. It should be `-mt-1` and `-ml-1` instead. Due to this error, the arrow of the tooltip is not positioned perfectly centered (it is slightly off-center) as can be seen in the reproducer.

```
    arrow: ({ context, props }) => ({
        class: [
            // [...]

            // Spacing
            {
                '-m-t-1 ': context?.right || (!context?.right && !context?.left && !context?.top && !context?.bottom),
                '-m-t-1': context?.left,
                '-m-l-1': context?.top || context?.bottom
            }
        ]
    }),
};

```

### Reproducer

https://stackblitz.com/edit/vitejs-vite-3heujr?file=src%2FApp.vue

### Steps to reproduce the behavior

Hover over the element with the tooltip. In the reproducer it's the text `Hover to see the tooltip`. The arrow of the tooltip is not perfectly centered.

### Expected behavior

The arrow of the tooltip should be perfectly centered.

**Comment by shayr1** [comment]
btw, I don't recommend using `ml` or `mr` anyways, rather use logicals such as `ms` and `me`

**Comment by atakantepe** [comment]
Hi, thank you for your PR. I merged it now🚀
