### ISSUE TITLE
Bug: Cannot override preset if using Tailwind important: true

### ISSUE THREAD

**Issue by martinszeltins** [primefaces/primevue-tailwind#58]
It is not possible to override a preset locally if project is using `important: true` in tailwind.config. It seems it would be better to use the [tailwind-merge](https://www.npmjs.com/package/tailwind-merge) library. I am referring to this: https://tailwind.primevue.org/guides/overriding-presets/#important

In some projects it is necessary to use `important: true` configuration.

For example, here the `!bg-blue-500` class won't work because all my Tailwind classes in my project are important because of `important: true` in my tailwind config.

```js
<InputText
  placeholder="Password"
  :pt="{ root: '!bg-blue-500' }"
  :pt-options="{ mergeSections: true, mergeProps: true }"
/>

tailwind.config.js
export default {
    content: [
        //
    ],
    important: true,
};
```

**Comment by mertsincan** [comment]
Hi @martinszeltins,

Could you please create an issue in PrimeVue Github? I think we can add a method to use custom merging libraries to core. Exp;
```
:pt-options="{ mergeSections: true, mergeProps: <function | boolean> }"

mergeProps: (global, self) => {
     //return // you can use tailwind-merge method with global.class and self.class
}
``

Best Regards,
