### ISSUE TITLE
Router active class not applied to MenuBar

### ISSUE THREAD

**Issue by notflip** [primefaces/primevue-tailwind#65]
I'm using the MenuBar as my main navigation, however I don't see any classes being applied on route changes, I'm using the router example.

```
<Menubar :model="items">
      <template #item="{ item, props, hasSubmenu }">
        <router-link v-if="item.route" v-slot="{ href, navigate }" :to="item.route" custom>
          <a :href="href" v-bind="props.action" @click="navigate">
            <span :class="item.icon" />
            <span>{{ item.label }}</span>
          </a>
        </router-link>
        <a v-else href="item.url" :target="item.target" v-bind="props.action">
          <span :class="item.icon" />
          <span>{{ item.label }}</span>
          <span v-if="hasSubmenu" class="pi pi-fw pi-angle-down" />
        </a>
      </template>
    </Menubar>
```

When navigating to the `/news` page, I see no active class being added to that menu item, is something missing or do I need some other setting perhaps? Thanks.

**Comment by atakantepe** [comment]
Hi, you can use https://v3.router.vuejs.org/api/#router-link routerlink :isActive for adding active classes. 👍

PrimeVue unstyled not support :isActive
