### ISSUE TITLE
MultiSelect placeholder font size and color

### ISSUE THREAD

**Issue by go4cas** [primefaces/primevue-tailwind#71]
I have created a component set, using the Tailwind Builder, and selecting the `Wind` preset.

The `MultiSelect` component's placeholder font is larger than other form components, and the text color is the standard colour, and not the lighter text color used for other component's placeholders.

<img width="563" alt="Screenshot 2024-01-15 at 12 55 43" src="https://github.com/primefaces/primevue-tailwind/assets/12674784/cd5c4abd-dea9-4620-9062-84b63bc6d9ae">

**Comment by mertsincan** [comment]
Thanks a lot for your report! We'll check and fix asap.

**Comment by atakantepe** [comment]
Hi,
Can you check if the styles come from the parent div? 

 Because I had a similar issue when adding them to headers in Datatable. The placeholder classes are all the same, 'placeholder:text-surface-400 dark:placeholder:text-surface-500', and font size shouldn't change as well.

**Comment by atakantepe** [comment]
Hi, I will close this issue, but if the issue persists please re-open it 👍
