### ISSUE TITLE
ConfirmDialog rejectButton/acceptButton Pass Through not working

### ISSUE THREAD

**Issue by IfnotFr** [primefaces/primevue-tailwind#72]
I am using the `ConfirmDialog` component and I tried to customize the look of the `rejectButton` and `acceptButton` using Pass Through parameter according to : https://primevue.org/confirmdialog/#pt.doc.confirmdialog but with no luck ...

Example :
`<ConfirmDialog :pt="{ rejectButton: { class: 'hidden' } }"></ConfirmDialog>`

Is still showing the reject button, and no class hidden were added to the button.

**Comment by mertsincan** [comment]
Hi,

RejectButton uses the pt keys of Button component. Please check https://primevue.org/button/#pt.doc.button

```
<ConfirmDialog
    :pt="{
      headerTitle: { class: 'text-primary' },
      rejectButton: {
        root: 'TEST',
      },
    }"
  ></ConfirmDialog>
```

**Comment by IfnotFr** [comment]
Oh, sorry for this issue, thanks for your response.

@mertsincan Maybe adding the link of the button documentation to the pt section will help newcomers like me.

As pt is a little complex to understand at first, but is a basic requirement for the tailwind version of primevue, maybe adding some help into the doc like this kind of links (to the target components) will bring users to the right direction.
