### ISSUE TITLE
Datatable error

### ISSUE THREAD

**Issue by csakiss26** [primefaces/primevue-tailwind#73]
I tried to use the Lara or Wind presets on my application. I got this error
`index.js:111  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'frozen')`
if I did not add the `frozen` property  to my Columns.

**Comment by mertsincan** [comment]
Thanks a lot for your report! We'll check and fix it before the next version is released.

**Comment by atakantepe** [comment]
Hi, today we will have a catchup release for the new version of PrimeVue. Can you try this with the latest PrimeVue? This was a core issue, and it has been fixed.

I'll be closing this. If the issue continues, please reopen it🙏

**Comment by claushellsing** [comment]
Tested on version 3.50 and it is still there
