### ISSUE TITLE
Unable to set the width on the sidebar component

### ISSUE THREAD

**Issue by tripex** [primefaces/primevue-tailwind#75]
Have tried the following just to see if my class gets passed to the <div> element, but it does not seem to happen.

`<Sidebar v-model:visible="visible" header="Sidebar" class="tester" :class="testertester">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </Sidebar>`

        "primeicons": "^6.0.1",
        "primevue": "^3.40.1",
        "vue": "^3.3.4"

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your report! But, I think this issue is related to PrimeVue core. Can you please create an issue with a sample stackblitz link in PrimeVue Github?

Best Regards,
