### ISSUE TITLE
Need size option for another Form Component

### ISSUE THREAD

**Issue by adiramardiani** [primefaces/primevue-tailwind#76]
First of All, thanks for this great library 

Actually, this issue is not only for tailwind only, but for non-unstyled standards as well, but because it will eventually be implemented in the Tailwind preset, and there are not too many issues here, so I wrote it here, again sorry.

Some common and existing form components will eventually be combine with other form components, and that's where I have problems with input field size consistency. size / height each component is not same 

Currently the size option is only in `InputText`, for dropdown types, trees, or other combination input fields such as text input in drop down filters do not have a size option.  also inside datatable, and other from data group or other component group.

At first I tried to make the size the same in global PT, but many cases in my application that each page, have a different size, and it is not possible to set in global PT, so complicated. Unfortunately this size option is only in `InputText`, and it makes me think about switching to another 3rd party, but I have fallen in love with Prime :(

My example is not perfect, far from perfect, but I hope you got the idea @atakantepe @cagataycivici 
https://stackblitz.com/edit/yzz7yr?file=src%2FApp.vue

![image](https://github.com/primefaces/primevue-tailwind/assets/8703419/8892b595-8592-4ffa-b6b0-e32d36954e81)

**Comment by mertsincan** [comment]
Thanks a lot for your interest! Good news! we recently announced our next-gen Aura theme. In this theme, we work in great detail on the components to make sure everything is pixel-perfect. Therefore, this feedback is very valuable for us. You can be sure that I will forward these to our design team as soon as possible.

https://www.reddit.com/r/vuejs/comments/19em9ql/introducing_the_allnew_aura_theme_for_primevue/

**Comment by adiramardiani** [comment]
Yes, I've seen it and it's very impressive, at the moment I haven't decided on a theme for my project, whether style/unstyled, but after see aura, for sure I will use aura. 3 word for aura, very detail, consistent, and pixel perfect ❤️ 

One funny thing netizens are crazy about the dashboard design in aura on twitter and other media, many think it's a template with many page like sakai (I hope so), but even the sample dashboard is very well received by the crowd 👍 🙌 

To be honest, compared to the material presets for tailwind, I prefer the Aura preset to first added in Tailwind Primevue accompanying PrimeOne and Wind Presets, the theme can be primary brand design for primevue, so I think is worth to have aura on tailwind preset to @cagataycivici @mertsincan 

For prime team
Thank you for your ideas, your passion, your ambition in the ui vue component community
