### ISSUE TITLE
Sidebar and dialog mask elements are not being animated

### ISSUE THREAD

**Issue by dencs08** [primefaces/primevue-tailwind#79]
None of the mask / backdrop elements are animated (sidebar mask, dialog mask).

it appears that mask elements are not being animated also on tailwind.primvue.org site - maybe it's a nuxt module problem becasue the tailwind.primevue.org is also built with this stack.
[tailwind.primevue.org/sidebar](https://tailwind.primevue.org/sidebar/)
[tailwind.primevue.org/dialog](https://tailwind.primevue.org/dialog/)

while it works fine on the main primevue:
[primevue.org/sidebar](https://primevue.org/sidebar/)
[primevue.org/dialog](https://primevue.org/dialog/)

the issue was raised also here
https://github.com/primefaces/primevue/issues/4920

renky solution from the link above works fine as the workaround for the time being.

**using:**
+ nuxt-primevue module unstyled.
+ lara theme from tailwind.primevue.org

**Comment by atakantepe** [comment]
Hi, thank you for letting us know. It will be in today's release 🌟
