### ISSUE TITLE
MenuItem styling missing

### ISSUE THREAD

**Issue by Quadrubo** [primefaces/primevue-tailwind#8]
The styling for MenuItems is currently missing. The provided code from [https://tailwind.primevue.org/menu/#template](https://tailwind.primevue.org/menu/#template) also doesn't match it's example.

**Comment by mertsincan** [comment]
Sorry for the delayed response! I think this issue has already been fixed in demo. https://stackblitz.com/run?file=src%2FApp.vue

Closed for now. If the problem persists, please reopen this ticket. Thanks a lot for your understanding!
Best Regards,
