### ISSUE TITLE
Inertiajs SplitButton size issue

### ISSUE THREAD

**Issue by aasiph** [primefaces/primevue-tailwind#81]
SplitButton is rendered incorrectly with laravel inertiajs tailwind. In normal vue vite app it works correctly.
![chrome_sJZEmJERCF](https://github.com/primefaces/primevue-tailwind/assets/312443/f0ed4b55-97cd-4bbf-838e-0cd2239f339d)

Inspecting in chrome dev tools I see height is 42px more than that of demo which is 30px in small variant size. An the reason behind the 42px height is the text height of the button label which is 26px compared to the demo which has 14px.
![chrome_TYeKuwwAcq](https://github.com/primefaces/primevue-tailwind/assets/312443/3ccf964e-2b23-4fc1-b29c-4a2a1d8ca5d8)

I have set all the font settings same as demo on https://tailwind.primevue.org/splitbutton/#sizes

**Comment by mertsincan** [comment]
Interesting! Is there any sample to test it? Or could you please attach a stackblitz link for us to replicate? I set a milestone for this ticket.
