### ISSUE TITLE
Lara SplitButton Small Font Size

### ISSUE THREAD

**Issue by mattlyons0** [primefaces/primevue-tailwind#82]
The tailwind class assigned to the small splitbutton preset is `text-xs` which corresponds to `0.75rem` (using default tailwind configuration) although the non tailwind implementation in lara is set to `0.875rem` (corresponding to `text-sm` tailwind class).

Non tailwind lara implementation: https://codesandbox.io/p/devbox/primevue-demo-jvrcgf
Tailwind lara implementation: https://github.com/primefaces/primevue-tailwind/blob/a8fd7eba5b8c2ccff3bad987b1762795b0cde73d/presets/lara/splitbutton/index.js#L24

The (non split) button implementation uses the correct font size: https://github.com/primefaces/primevue-tailwind/blob/a8fd7eba5b8c2ccff3bad987b1762795b0cde73d/presets/lara/button/index.js#L13

The large splitbutton also seems correct

**Comment by mattlyons0** [comment]
It might also be worth discussing this holistically with button padding, it seems to be quite a bit off from lara:

| Size (Font Size) | Lara Padding (Y x X) | Lara Tailwind Preset Padding (Y x X) |
|--------|--------|--------|
| Small (0.875rem) | 0.65625rem x 1.09375rem | 0.5rem x 0.75rem (py-2 px-3) |
| Regular (1rem) | 0.75rem x 1.25rem |  0.75rem x 1rem (py-3 px-4) |
| Large (1.25rem) |  0.9375rem x 1.5625rem |  0.75rem x 1rem (py-3 px-4) |

If alignment between the themes is intended (although not pixel perfect to use tailwind default units), I'd change it to this:
| Size (Font Size) | Lara Padding (Y x X) | Proposed Lara Tailwind Preset Padding (Y x X) |
|--------|--------|--------|
| Small (0.875rem) | 0.65625rem x 1.09375rem | 0.625rem x 1rem (py-2.5 px-4) |
| Regular (1rem) | 0.75rem x 1.25rem |  0.75rem x 1.25rem (py-3 px-5) |
| Large (1.25rem) |  0.9375rem x 1.5625rem |  1rem x 1.5rem (py-4 px-6) |

Large is kinda split in the middle between `py-4` and `py-3.5` so it could really go either way. Same is less true of small's `py-2.5` but the difference is definitely noticeable.

**Comment by mertsincan** [comment]
Woww, thanks a lot for the detailed information and PR! I set a milestone for this ticket. We'll check it before the milestone is released.

**Comment by atakantepe** [comment]
Thank you for providing detailed information and the PR. I have merged it, and it will be included in today's release.🔥
