### ISSUE TITLE
Missing "File upload" preset for Tailwind

### ISSUE THREAD

**Issue by FalkoJoseph** [primefaces/primevue-tailwind#85]
Hi guys, 

First of all amazing job with this project. The Tailwind presets are really clean and help me speed up my workflow by a thousand times.

However, one question. I'm using the builder to create my own templates based on the Lara preset, but I don't seem to be able to select the file upload component. (screenshot 1)

When importing the file upload component via `import FileUpload from 'primevue/fileupload';` it's pretty much unstyled (screenshot 2)

![Falko 2024-01-25 at 00 06 23@2x](https://github.com/primefaces/primevue-tailwind/assets/556086/12ca6c0a-aaf4-494f-9177-e17e7796dad2)

![Falko 2024-01-25 at 00 08 49@2x](https://github.com/primefaces/primevue-tailwind/assets/556086/6236f3d4-1abc-4613-bf4f-bf1b5c548ff9)

Am I doing something wrong, or is there no support for file upload yet?

Thanks in advance.

**Comment by FalkoJoseph** [comment]
Resolved it already. Actually needed very little work to theme myself, don't think a preset is that necessary. :-)

**Comment by jsodeman** [comment]
> Resolved it already.

Could you post your solution?

**Comment by FalkoJoseph** [comment]
> > Resolved it already.
> 
> Could you post your solution?

In my case since the File Upload component primarily exists of existing components such as buttons, all I had to do was styling the drop & drop zone and applying my own button styling to the File Upload buttons.

In my case this was all it took. I added this to my `buttons.css`.

```
/* ==========================================================================
   Primevue File upload
   ========================================================================== */

.btn,
[data-pc-name="button"],
[data-pc-section="choosebutton"] {
}

.btn-primary,
[data-pc-section="choosebutton"] {
}

.btn-default,
[data-pc-section="cancelbutton"] {
}

input[type="file"][data-pc-section="input"] {
  @apply hidden;
}

[data-pc-name="fileupload"] {
  & [data-pc-section="content"] {
  }
}
```

**Comment by Robin-Hoodie** [comment]
An alternative to what @FalkoJoseph  suggested is using Passthrough options to style each part of the component. The Pass Through tab on https://primevue.org/fileupload/ is very helpful in doing so. Also vital is to use `hidden` on the `input` passthrough prop - as @FalkoJoseph helpfully demonstrated
