### ISSUE TITLE
PrimeVue Tailwind Dropdown Use the wrong Input style when value = 0 or value = false

### ISSUE THREAD

**Issue by ikiet** [primefaces/primevue-tailwind#86]
Hi,
Thanks for this great project.
I currently have a problem when using the Dropdown with value = 0 or value = false.
When the value with 0 or false selected, grayed-out style will be used.

<img width="509" alt="image" src="https://github.com/primefaces/primevue-tailwind/assets/148988807/87fd0a12-3c98-4a56-9196-eb6d1d0823f5">

Here is the Stackblitz link:

https://stackblitz.com/edit/xtq1pz-cuqhsk?file=src%2FApp.vue

I found the problem because of the condition check in the dropdown/index.js file.

```
            { 'text-surface-800 dark:text-white/80': props.modelValue, 'text-surface-400 dark:text-surface-500': !props.modelValue },
```

It will be OK if I fix it like below.
```
            { 'text-surface-800 dark:text-white/80': props.modelValue != undefined, 'text-surface-400 dark:text-surface-500': props.modelValue == undefined },
```

If you think this fix is better, let me know so I can create a new PR. Thanks

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your report! I set a milestone for it, I hope you contribute to this project with PR :)
