### ISSUE TITLE
Import PrimeVue Core's Update Changes (v3.46.0 -> v3.47.x)

### ISSUE THREAD

**Issue by atakantepe** [primefaces/primevue-tailwind#89]
Affected Components;

- [x]  Slider
- [x]  DataTable (Checkbox and RadioButton)
- [x]  Checkbox
- [x]  RadioButton
- [x]  TriStateCheckbox
- [x]  InputSwitch
- [x]  ToggleButton
- [x]  MultiSelect (Checkbox)
- [x]  TreeTable (Checkbox)
- [x]  Tree (Checkbox)
- [x]  TreeSelect (Checkbox)

 
####  Changes on PrimeVue Core

- https://github.com/primefaces/primevue/issues/5020
- https://github.com/primefaces/primevue/issues/5071

**Comment by atakantepe** [comment]
Also mentioned here [#88](https://github.com/primefaces/primevue-tailwind/issues/88)

**Comment by firlottea** [comment]
Looks like it's only presets that have been update to fix this.
Is 
`import Tailwind from "primevue/passthrough/tailwind";` (to use with `usePassThrough()`)
Not supported anymore? Or should an issue be created?
