### ISSUE TITLE
MultiSelect checkbox spacing and checked icon problem

### ISSUE THREAD

**Issue by jsodeman** [primefaces/primevue-tailwind#98]
The checkbox on the Multiselect has no spacing with the option label, and the checked state icon isn't aligned correctly.

Tested with both Lara and Wind presets, no other custom CSS.

`<MultiSelect :options="userOptions" v-model="shareUsers" placeholder="Select Users"
				optionLabel="label" optionValue="value" />`

![image](https://github.com/primefaces/primevue-tailwind/assets/2388842/73787b8e-abe8-4cdb-aa76-7669c986cc7b)

from main.js
```
app.use(PrimeVue, {
	unstyled: true,
	pt: Lara,
});
```

style.css
```
@tailwind base;
@tailwind components;
@tailwind utilities;

// :root colors etc
```

**Comment by atakantepe** [comment]
Hi, if you are using PrimeVue 3.47.x, this issue was from the core changes. These are fixed now. 

You can check here for the issue and the release ⬇️

https://github.com/primefaces/primevue-tailwind/issues/89

https://github.com/primefaces/primevue-tailwind/releases/tag/0.6.0
